### ISSUE TITLE
map() on (empty) joined input stream panics

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#1191]
The following query (with same dataset as attached to #1190) panics:

```
        join(tables: {

        lhs: from(bucket: "prometheus")
        	|> range(start: 2019-02-21T16:45:30Z, stop: 2019-02-21T16:51:40Z)
        	|> filter(fn: (r) =>
        		(r._measurement == "demo_cpu_usage_seconds_total"))
        	|> window(every: 10000000000ns, period: 5m)
        	|> filter(fn: (r) =>
        		(r._stop >= 2019-02-21T16:50:30Z and r._start <= 2019-02-21T16:46:40Z))
        	|> last()
        	|> timeShift(duration: 0ns),

        rhs: from(bucket: "prometheus")
        	|> range(stop: 2019-02-21T16:51:40Z, start: 2019-02-21T16:45:30Z)
        	|> filter(fn: (r) =>
        		(r._measurement == "demo_cpu_usage_seconds_total"))
        	|> window(every: 10000000000ns, period: 5m)
        	|> filter(fn: (r) =>
        		(r._stop >= 2019-02-21T16:50:30Z and r._start <= 2019-02-21T16:46:40Z))
        	|> last()
        	|> timeShift(duration: 0ns)},
        on: ["_start", "_stop"])

        	|> map(fn: (r) =>
        		({_value: r._value_lhs / r._value_rhs, _stop: r._stop, _time: r._stop}))
```

The `map()` does not panic on a simple other empty input stream, nor does it panic if I add an `on` argument to the `join()` to make the `map()` input non-empty. Not sure what exactly causes the panic.

The panic is logged like this:

```
2019-04-20T09:15:51.734144Z	info	Dispatcher panic	{"log_id": "0EvUCAhW000", "service": "storage-reads", "component": "dispatcher", "error": "runtime error: invalid memory address or nil pointer dereference"}
goroutine 6126 [running]:
runtime/debug.Stack(0xc0279b9e00, 0x1c1c000, 0x180b0f2)
	/home/julius/go/src/runtime/debug/stack.go:24 +0x9d
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc0279b9e60)
	/home/julius/gosrc/src/github.com/influxdata/flux/execute/dispatcher.go:75 +0x270
panic(0x15cb060, 0x2bb0cd0)
	/home/julius/go/src/runtime/panic.go:522 +0x1b5
github.com/influxdata/flux/execute.(*ColListTableBuilder).NRows(...)
	/home/julius/gosrc/src/github.com/influxdata/flux/execute/table.go:529
github.com/influxdata/flux/stdlib/universe.(*MergeJoinCache).ForEachWithContext.func1(0x1c74a60, 0xc005c6b7c0, 0x159cd20, 0x2d84170)
	/home/julius/gosrc/src/github.com/influxdata/flux/stdlib/universe/join.go:617 +0x226
github.com/influxdata/flux/execute.(*GroupLookup).Range(0xc006ee3da0, 0xc027e7dbf0)
	/home/julius/gosrc/src/github.com/influxdata/flux/execute/group_lookup.go:272 +0xa9
github.com/influxdata/flux/stdlib/universe.(*MergeJoinCache).ForEachWithContext(0xc0291a11e0, 0xc00c0d7d40)
	/home/julius/gosrc/src/github.com/influxdata/flux/stdlib/universe/join.go:595 +0xa6
github.com/influxdata/flux/execute.(*dataset).evalTriggers(0xc006ee45f0, 0x20000c0291a1338, 0xffffffffffffffff)
	/home/julius/gosrc/src/github.com/influxdata/flux/execute/dataset.go:113 +0x8c
github.com/influxdata/flux/execute.(*dataset).UpdateWatermark(0xc006ee45f0, 0x15856f3050941800, 0xc027e7dcf8, 0xc0291a1340)
	/home/julius/gosrc/src/github.com/influxdata/flux/execute/dataset.go:88 +0x38
github.com/influxdata/flux/stdlib/universe.(*mergeJoinTransformation).UpdateWatermark(0xc023674c80, 0xd65ab281196cc85b, 0x823bcd9f2a49a695, 0x15856f3050941800, 0x0, 0x0)
	/home/julius/gosrc/src/github.com/influxdata/flux/stdlib/universe/join.go:309 +0x179
github.com/influxdata/flux/execute.processMessage(0x1c55ca0, 0xc023674c80, 0x1c34280, 0xc00c0c6260, 0x0, 0x0, 0x0)
	/home/julius/gosrc/src/github.com/influxdata/flux/execute/transport.go:202 +0x2d6
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc0279a83c0, 0xa)
	/home/julius/gosrc/src/github.com/influxdata/flux/execute/transport.go:156 +0xa1
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc0279b9e60, 0x1c4eca0, 0xc006ede880)
	/home/julius/gosrc/src/github.com/influxdata/flux/execute/dispatcher.go:126 +0x4b
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc0279b9e60, 0x1c4eca0, 0xc006ede880)
	/home/julius/gosrc/src/github.com/influxdata/flux/execute/dispatcher.go:80 +0x95
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/home/julius/gosrc/src/github.com/influxdata/flux/execute/dispatcher.go:61 +0x7e
[...]
```

**Comment by juliusv** [comment]
(accidentally created the issue before my text was fully written, if you're reading this by email, I edited the initial description)
