### ISSUE TITLE
Panic in semantic analysis when no RHS to pipe-forward

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#1291]
This query produces a panic:
```
from(bucket: "my-bucket") |>
```
Here's the stack:
```
goroutine 103 [running]:
github.com/influxdata/flux/semantic.analyzeCallExpression(0x0, 0x0, 0x0, 0x0)
	/Users/cwolff/workspace/github.com/influxdata/flux/semantic/analyze.go:404 +0x3a
github.com/influxdata/flux/semantic.analyzePipeExpression(0xc000410e40, 0x1, 0x0, 0x0)
	/Users/cwolff/workspace/github.com/influxdata/flux/semantic/analyze.go:470 +0x33
github.com/influxdata/flux/semantic.analyzeExpression(0x20110a0, 0xc000410e40, 0x0, 0x77deb6186eb2f74c, 0x0, 0x77deb6186eb2f74c)
	/Users/cwolff/workspace/github.com/influxdata/flux/semantic/analyze.go:266 +0x788
github.com/influxdata/flux/semantic.analyzeExpressionStatement(0xc0005996e0, 0x0, 0x77deb6186eb2f74c, 0x57d6420ad2bc777a)
	/Users/cwolff/workspace/github.com/influxdata/flux/semantic/analyze.go:201 +0x4d
github.com/influxdata/flux/semantic.analyzeStatment(0x2010c20, 0xc0005996e0, 0x1, 0xc000539ca0, 0x1, 0x0)
	/Users/cwolff/workspace/github.com/influxdata/flux/semantic/analyze.go:127 +0x601
github.com/influxdata/flux/semantic.analyzeFile(0xc0002228c0, 0xc0002239d0, 0x1, 0xc00056d420)
	/Users/cwolff/workspace/github.com/influxdata/flux/semantic/analyze.go:62 +0x372
github.com/influxdata/flux/semantic.analyzePackage(0xc0005d4a20, 0x201d340, 0xc00053fcd0, 0x40bac9)
	/Users/cwolff/workspace/github.com/influxdata/flux/semantic/analyze.go:31 +0xf2
github.com/influxdata/flux/semantic.New(0xc0005d4a20, 0x28, 0xc0004d27e0, 0x1f7f170)
	/Users/cwolff/workspace/github.com/influxdata/flux/semantic/analyze.go:13 +0x2f
github.com/influxdata/flux.EvalAST(0xc0005d4a20, 0xc00053fde0, 0x1, 0x1, 0xc0004d27e0, 0x4, 0x0, 0x0, 0x0, 0x20296e0, ...)
	/Users/cwolff/workspace/github.com/influxdata/flux/compile.go:47 +0x40
github.com/influxdata/flux/internal/spec.FromAST(0x1ff2420, 0xc0004d2750, 0xc0005d4a20, 0x271db69a, 0xed4712c63, 0x0, 0x0, 0x0, 0x0)
	/Users/cwolff/workspace/github.com/influxdata/flux/internal/spec/build.go:37 +0x180
github.com/influxdata/flux/lang.(*AstProgram).Start(0xc0004d2360, 0x1ff2420, 0xc0004d2750, 0xc000013dc0, 0xc000420240, 0xc000485408, 0xc0004854b8, 0xc000368f78)
	/Users/cwolff/workspace/github.com/influxdata/flux/lang/compiler.go:298 +0xc8
github.com/influxdata/flux/control.(*Controller).executeQuery(0xc000564000, 0xc00051bce0)
	/Users/cwolff/workspace/github.com/influxdata/flux/control/controller.go:283 +0x105
github.com/influxdata/flux/control.(*Controller).processQueryQueue(0xc000564000)
	/Users/cwolff/workspace/github.com/influxdata/flux/control/controller.go:265 +0x4c
github.com/influxdata/flux/control.New.func1(0xc000564000)
	/Users/cwolff/workspace/github.com/influxdata/flux/control/controller.go:123 +0x57
created by github.com/influxdata/flux/control.New
	/Users/cwolff/workspace/github.com/influxdata/flux/control/controller.go:121 +0x524
```

**Comment by wolffcm** [comment]
Fixed by #1312.
