### ISSUE TITLE
Are tableFind(), getRecord() and getColumn() functions working?

### ISSUE THREAD

**Issue by StephenSorriaux** [influxdata/flux#1796]
Hi,

I am using InfluxDB 1.7.8 with Flux 0.36 and I am experiencing some difficulties with the new `tableFind()`, `getRecord()` and `getColumn()` [functions](https://docs.influxdata.com/flux/v0.36/functions/built-in/transformations/stream-table/tablefind/).

I am trying to use the result of a first table to be used as a filter for the next table. I find those functions that would seem to meet my needs but I am stuck with a `panic`:
```
panic: interface conversion: interface {} is nil, not influxdb.Dependencies

goroutine 1 [running]:
github.com/influxdata/influxdb/flux/stdlib/influxdata/influxdb.createReadFilterSource(0x1095b20, 0xc000101ae0, 0x4d5eccd93a5f1dca, 0xb8e093295a108e, 0x10a5c20, 0xc000217440, 0x0, 0xc000715d00, 0x4521cd, 0xc92540)
	/go/src/github.com/influxdata/influxdb/flux/stdlib/influxdata/influxdb/source.go:141 +0x5f5
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*createExecutionNodeVisitor).Visit(0xc0002370a0, 0x10aaee0, 0xc00057e630, 0x19be400, 0xc000716228)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:196 +0x4ad
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*createExecutionNodeVisitor).Visit-fm(0x10aaee0, 0xc00057e630, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:108 +0x3e
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/plan.walk(0x10aaee0, 0xc00057e630, 0xfcd730, 0xc000716330, 0xc000716198, 0x1, 0x2)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/plan/walk.go:88 +0x1bf
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/plan.walk(0x10aaee0, 0xc00057e3f0, 0xfcd730, 0xc000716330, 0xc000716198, 0x1, 0x40d56f)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/plan/walk.go:82 +0x178
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/plan.(*Spec).BottomUpWalk(0xc000216ac0, 0xc000716330, 0xc000208840, 0x10)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/plan/walk.go:60 +0x312
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executor).createExecutionState(0xc000597f30, 0x109f240, 0xc0002173c0, 0xc000216ac0, 0xc000237080, 0x109a001, 0xc000597f30, 0xc0007163b8)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:108 +0x1aa
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executor).Execute(0xc000597f30, 0x109f240, 0xc0002173c0, 0xc000216ac0, 0xc000237080, 0x0, 0xc000216440, 0xbf540ef607d4ba19, 0x1047b6ea76)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:73 +0x5d
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/lang.(*Program).Start(0xc000237060, 0x109f240, 0xc0002173c0, 0xc000237080, 0xc000237060, 0x0, 0x0, 0xc00024d440)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/lang/compiler.go:253 +0x159
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/stdlib/universe.tableFindCall(0x10ad220, 0xc0001bdf40, 0x30, 0xda49c0, 0xdba101, 0xc00024d440)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/stdlib/universe/table_fns.go:92 +0x3b7
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/values.(*function).Call(0xc0002227b0, 0x10ad220, 0xc0001bdf40, 0xc000421cb0, 0xdba1d3, 0x6, 0x10a4fc0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/values/function.go:110 +0x3e
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc000509540, 0xc0005f5180, 0x10a96e0, 0xc000421cb0, 0x0, 0x0, 0x0, 0xc000447a20)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:527 +0x3d1
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc000509540, 0x10a4fc0, 0xc0005f5180, 0x10a96e0, 0xc000421cb0, 0x10abe00, 0xc0002366c0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:243 +0x1e67
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doArguments(0xc000509540, 0xc0000c38c0, 0x10a96e0, 0xc000421cb0, 0xdb9970, 0x5, 0x10a4fc0, 0xc0005f5180, 0x5, 0xc0000f63c0, ...)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:559 +0x35f
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc000509540, 0xc0005f50a0, 0x10a96e0, 0xc000421cb0, 0x0, 0x40b700, 0xce6720, 0xd46600)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:507 +0x292
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc000509540, 0x10a4fc0, 0xc0005f50a0, 0x10a96e0, 0xc000421cb0, 0xd90100, 0xc0002366a0, 0x1786da0, 0xc0002366a0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:243 +0x1e67
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doVariableAssignment(0xc000509540, 0xc00045b2c0, 0x10a96e0, 0xc000421cb0, 0xc0006da600, 0x4, 0xdb8d21, 0xc000509568)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:198 +0x5d
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doStatement(0xc000509540, 0x10a5440, 0xc00045b2c0, 0x10a96e0, 0xc000421cb0, 0xc0005f41c0, 0xc00075d3e0, 0x40d0e3, 0x7f7eef44f750)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:167 +0x5c1
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doFile(0xc000509540, 0xc00016e180, 0x10a96e0, 0xc000421cb0, 0x1096160, 0xc00011b658, 0x8, 0xc00011a0c0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:110 +0x1b1
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doPackage(0xc000509540, 0xc0005f41c0, 0x10a96e0, 0xc000421cb0, 0x1096160, 0xc00011b658, 0x1096c60, 0xc00011a008)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:93 +0xa1
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doRoot(0xc000509540, 0x10a27c0, 0xc0005f41c0, 0x10a96e0, 0xc000421cb0, 0x1096160, 0xc00011b658, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:76 +0x154
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).Eval(0xc000509540, 0x10a27c0, 0xc0005f41c0, 0x10a96e0, 0xc000421cb0, 0x1096160, 0xc00011b658, 0xc0000c3500, 0xc0003f95d0, 0x79773b, ...)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:67 +0x309
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux.EvalAST(0xc0000c3500, 0xc0003f9708, 0x1, 0x1, 0x0, 0xc0002e9670, 0x435cdf, 0xc000000300, 0x200000003, 0xc000000300, ...)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/compile.go:59 +0x22b
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux.Eval(0xc0001461c0, 0xdc, 0xc0003f9708, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc0000ac058, ...)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/compile.go:42 +0xb3
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/repl.(*REPL).executeLine(0xc00024d080, 0xc0001461c0, 0xdc, 0xc0000ac050, 0x0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/repl/repl.go:137 +0xc4
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/repl.(*REPL).input(0xc00024d080, 0xc0001461c0, 0xdc)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/repl/repl.go:117 +0x43
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/repl.(*REPL).input-fm(0xc0001461c0, 0xdc)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/repl/repl.go:46 +0x3e
github.com/influxdata/influxdb/vendor/github.com/c-bata/go-prompt.(*Prompt).Run(0xc0000f5d40)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/c-bata/go-prompt/prompt.go:77 +0x63f
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/repl.(*REPL).Run(0xc00024d080)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/repl/repl.go:58 +0x1d9
github.com/influxdata/influxdb/cmd/influx/cli.(*CommandLine).Run(0xc0005b5500, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/cmd/influx/cli/cli.go:214 +0xa2a
main.main()
	/go/src/github.com/influxdata/influxdb/cmd/influx/main.go:127 +0x875
```
Flux query is same as the one provided in the [example](https://docs.influxdata.com/flux/v0.36/functions/built-in/transformations/stream-table/getrecord/#example)

Thank you

**Comment by nathanielc** [comment]
@StephenSorriaux They do not yet work, but we are actively working on the issues around those functions. See #1795 and #1799

**Comment by StephenSorriaux** [comment]
@nathanielc Thank you for the answer, I will follow those 2 issues then
