### ISSUE TITLE
panic when calling monitor.notify

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#1814]
```json
{"code":"internal error","message":"panic","error":"unexpected kind: got \"object\" expected \"nil\", trace: goroutine 25656 [running]:\nruntime/debug.Stack(0xc001df3178, 0x40, 0xc001df3168)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/influxdata/flux/values.UnexpectedKind(0xc, 0x1, 0x1, 0x1)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/values/values.go:331 +0x34\ngithub.com/influxdata/flux/values.CheckKind(0xc, 0x1)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/values/values.go:364 +0x74\ngithub.com/influxdata/flux/compiler.(*memberEvaluator).Eval(0xc00384f2f0, 0x263ac40, 0xc004cddc40, 0x2632880, 0xc0038eca50, 0x2679e00, 0xc005039800, 0x2680420, 0xc001966500, 0x0, ...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:548 +0x162\ngithub.com/influxdata/flux/compiler.eval(...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:99\ngithub.com/influxdata/flux/compiler.(*objEvaluator).Eval(0xc002253760, 0x263ac40, 0xc004cddc40, 0x2632880, 0xc0038eca50, 0x2679e00, 0xc005039800, 0x2680420, 0xc001df33a0, 0x2680420, ...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:222 +0x1b7\ngithub.com/influxdata/flux/compiler.(*callEvaluator).Eval(0xc00384f3b0, 0x263ac40, 0xc004cddc40, 0x2632880, 0xc0038eca50, 0x2679e00, 0xc005039800, 0x2680420, 0xc0019664c0, 0x0, ...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:585 +0x8c\ngithub.com/influxdata/flux/compiler.eval(...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:99\ngithub.com/influxdata/flux/compiler.(*binaryEvaluator).Eval(0xc002efd040, 0x263ac40, 0xc004cddc40, 0x2632880, 0xc0038eca50, 0x2679e00, 0xc005039800, 0x1c4b4e0, 0xc00384fa10, 0xc004230600, ...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:329 +0x121\ngithub.com/influxdata/flux/compiler.eval(...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:99\ngithub.com/influxdata/flux/compiler.(*objEvaluator).Eval(0xc0022536c0, 0x263ac40, 0xc004cddc40, 0x2632880, 0xc0038eca50, 0x2679e00, 0xc005039800, 0xc00474d8c8, 0xc00384f1a0, 0x3bc29f0, ...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:222 +0x1b7\ngithub.com/influxdata/flux/compiler.(*callEvaluator).Eval(0xc00384f410, 0x263ac40, 0xc004cddc40, 0x2632880, 0xc0038eca50, 0x2679e00, 0xc005039800, 0x267f980, 0xc0036fc8e0, 0x0, ...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:585 +0x8c\ngithub.com/influxdata/flux/compiler.eval(...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:99\ngithub.com/influxdata/flux/compiler.(*objEvaluator).Eval(0xc002253680, 0x263ac40, 0xc004cddc40, 0x2632880, 0xc0038eca50, 0x2679e00, 0xc005039800, 0x0, 0x0, 0x2680060, ...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:222 +0x1b7\ngithub.com/influxdata/flux/compiler.eval(...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:99\ngithub.com/influxdata/flux/compiler.(*blockEvaluator).Eval(0xc002efd100, 0x263ac40, 0xc004cddc40, 0x2632880, 0xc0038eca50, 0x2679e00, 0xc005039800, 0xc004636300, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:121 +0xbc\ngithub.com/influxdata/flux/compiler.eval(...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:99\ngithub.com/influxdata/flux/compiler.compiledFn.Eval(0x2607140, 0xc002efd100, 0x265f300, 0xc005c2c580, 0x2679e00, 0xc005039800, 0x263ac40, 0xc004cddc40, 0x2632880, 0xc0038eca50, ...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/compiler/runtime.go:66 +0xd6\ngithub.com/influxdata/flux/execute.(*rowFn).eval(0xc005cf49c0, 0x263ac40, 0xc004cddc40, 0x2632880, 0xc0038eca50, 0x0, 0x2673d00, 0xc003910a50, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/row_fn.go:174 +0x2d8\ngithub.com/influxdata/flux/execute.(*RowMapFn).Eval(0xc005cf49c0, 0x263ac40, 0xc004cddc40, 0x2632880, 0xc0038eca50, 0x0, 0x2673d00, 0xc003910a50, 0xc001df3b70, 0x40dd8b, ...)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/row_fn.go:240 +0x95\ngithub.com/influxdata/flux/stdlib/universe.(*mapTransformation).Process.func1(0x2673d00, 0xc003910a50, 0xc001df3cf0, 0x40c378)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/stdlib/universe/map.go:176 +0x2eb\ngithub.com/influxdata/flux/execute.(*ColListTable).Do(0xc003910a50, 0xc002efd180, 0xc00000e2f0, 0x20)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/table.go:1391 +0x78\ngithub.com/influxdata/flux/stdlib/universe.(*mapTransformation).Process(0xc003911c70, 0xc5270b5810546f5, 0x7954f2a480d8098a, 0x26484c0, 0xc003910a50, 0xc001b51e01, 0x43e931)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/stdlib/universe/map.go:173 +0x136\ngithub.com/influxdata/flux/execute.processMessage(0x2649c00, 0xc003911c70, 0x2607800, 0xc0036fc820, 0x0, 0x0, 0xc000797800)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/transport.go:199 +0x1e4\ngithub.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc005cf4a20, 0xa)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/transport.go:156 +0xa1\ngithub.com/influxdata/flux/execute.(*poolDispatcher).run(0xc005cf42a0, 0x263ac40, 0xc004cddc40)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/dispatcher.go:132 +0x4b\ngithub.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc005cf42a0, 0x263ac40, 0xc004cddc40)\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/dispatcher.go:86 +0x95\ncreated by github.com/influxdata/flux/execute.(*poolDispatcher).Start\n\t/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/dispatcher.go:63 +0x7e\n"}
```

```
package main
// Slack HTTP Messages
import "influxdata/influxdb/monitor"
import "http"
import "json"
import "experimental"

headers = {"Content-Type": "application/json"}
endpoint = http.endpoint(url: "https://slack.com/api/chat.postMessage?token=something&channel=general&text=joy&pretty=1")
notification = {
	_notification_rule_id: "046cf874f7e28000",
	_notification_rule_name: "Slack HTTP Messages",
	_notification_endpoint_id: "046cf85a1ad37000",
	_notification_endpoint_name: "Slack HTTP",
}
statuses = monitor.from(start: -2m)
crit = statuses
	|> filter(fn: (r) =>
		(r._level == "crit"))
all_statuses = crit
	|> filter(fn: (r) =>
		(r._time > experimental.subDuration(from: now(), d: 1m)))

all_statuses
	|> monitor.notify(data: notification, endpoint: endpoint(mapFn: (r) =>
		({headers: headers, data: json.encode(v: r)})))
```

**Comment by jlapacik** [comment]
I believe that panic comes from this line right here:
https://github.com/influxdata/flux/blob/78829ad4795e80e1fcaef2bf7531afbad8b050b4/compiler/runtime.go#L548

We ran into the same panic with the pagerduty endpoint. It was supposed to be commented out.
