### ISSUE TITLE
Panic when running `difference(columns: ["_time"])`

### ISSUE THREAD

**Issue by chnn** [influxdata/flux#189]
I attempted to run the following query:

```
from(bucket: "telegraf/autogen")
  |> range(start: -10m)
  |> filter(fn: (r) => r._measurement == "mem" and r._field == "active")
  |> difference(columns: ["_time"])
```

I received the following error:

```
#datatype,string,string
#group,true,true
#default,,
,error,reference
,"panic: unknown type invalid
goroutine 517 [running]:
runtime/debug.Stack(0x1c38be0, 0x1c0c440, 0xc001b09580)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc00108b440)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:73 +0xbc
panic(0x1c0c440, 0xc001b09580)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.PanicUnknownType(0x0)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/table.go:630 +0xad
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.ColListTableBuilder.AddCol(0xc000973310, 0xc001201fa0, 0x1db50fd, 0x5, 0x0, 0x1)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/table.go:435 +0x5a
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations.(*differenceTransformation).Process(0xc001b0a680, 0x5b571309707f64f3, 0xd82671cf6bc9dab5, 0xa437b88, 0xc0020baf00, 0x49501, 0xc000356d00)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations/difference.go:160 +0x192
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.processMessage(0x1f0c9c0, 0xc001b0a680, 0x1efb980, 0xc0008f9320, 0xc001622740, 0x11ea59d, 0xc00213fa50)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:199 +0x1fc
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc00108b4a0, 0xa)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:156 +0xa1
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages-fm(0xa)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:137 +0x34
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc00108b440, 0x1f089c0, 0xc001b0db60)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:126 +0x4b
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc00108b440, 0x1f089c0, 0xc001b0db60)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:80 +0x95
created by github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:61 +0x7e
",
```

I eventually wanted to pipe this query through `|> group(none: true) |> median()` as a way to estimate the sample rate of a series.

**Comment by jsternberg** [comment]
@nathanielc the primary cause of this panic seems to be that we try to add an invalid column type instead of returning an error saying that difference doesn't handle times. At the same time, it seems reasonable to me to find the difference between times.
