### ISSUE TITLE
panic when running various `group` calls

### ISSUE THREAD

**Issue by chnn** [influxdata/flux#214]
I'm seeing a panic when running this query:

```
from(bucket:"telegraf") |> range(start:-30s) |> group(by: ["_measurement"])
```

Panic:

```
#datatype,string,string
#group,true,true
#default,,
,error,reference
,"panic: column _value is not of type int
goroutine 5549 [running]:
runtime/debug.Stack(0x1c2c780, 0x1c00360, 0xc001cd7b10)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc0019d3920)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:73 +0xbc
panic(0x1c00360, 0xc001cd7b10)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.CheckColType(0x1dacbcb, 0x6, 0x4, 0x2)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/table.go:845 +0xff
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*table).Ints(0xc0008e00f0, 0x3, 0x0, 0x0, 0x0)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/table.go:70 +0x6a
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.AppendMappedRecordWithDefaults(0x0, 0x1f0f3e0, 0xc0008e00f0, 0x1f1ab00, 0xc001cd7590, 0xc000f565a0, 0xb, 0xb, 0xb, 0xb)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/table.go:236 +0x211
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations.(*groupTransformation).Process.func1(0x1f0f3e0, 0xc0008e00f0, 0xc0008e00f0, 0x1)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations/group.go:227 +0x1d6
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*floatTable).Do(0xc0008e00f0, 0xc000ceab40, 0x0, 0x0)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/table.gen.go:60 +0x84
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations.(*groupTransformation).Process(0xc002700680, 0x2c5592f951af46ff, 0xedb8c7731fd71592, 0x3cf9288, 0xc0008e00f0, 0x50201, 0xc000290600)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations/group.go:216 +0x26e
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.processMessage(0x1f07da0, 0xc002700680, 0x1ef6760, 0xc000eeebc0, 0xc00295cf68, 0x11eb53d, 0xc000282410)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:199 +0x1fc
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc0019d3980, 0xa)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:156 +0xa1
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages-fm(0xa)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:137 +0x34
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc0019d3920, 0x1f035e0, 0xc000150e70)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:126 +0x4b
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc0019d3920, 0x1f035e0, 0xc000150e70)
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:80 +0x95
created by github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/Users/chris/Dev/Go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:61 +0x7e
",
```

It seems to be related to type inference. Here are similar queries that will always cause similar panics:

```
from(bucket:"telegraf") |> range(start:-30s) |> group(none: true)
from(bucket:"telegraf") |> range(start:-30s) |> group(all: true)
```

This similar query does **not** cause a panic:

```
from(bucket:"telegraf") |> range(start:-30s) |> group(by: ["_field"])
```

**Comment by chnn** [comment]
Ok thanks. Here's the full query where we first ran into the issue:

```
from(bucket:"telegraf")
  |> range(start: -1d)
  |> group(by: ["_measurement"])
  |> distinct(column: "_measurement")
  |> group(none: true) 
```

We're using it to get a list of measurements in a bucket, so we can't filter by a particular measurement.

**Comment by nathanielc** [comment]
@wolffcm Looks like we need to add the planner rewrite rule to push down the distinct call to avoid the panic in this case. This was an optimization that we had in the old planner that avoided the column type issue because the storage API calls did not have to return any time series data, only the metadata.  @stuartcarnie Added the RPC call for this optimization.
