### ISSUE TITLE
Panic on push down filter rule

### ISSUE THREAD

**Issue by affo** [influxdata/flux#2381]
I get the following panic on `v0.58.4`:

```
runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 456 [running]:
runtime/debug.Stack(0xc002d536e0, 0x1d17f00, 0x2064abe)
	/usr/local/Cellar/go/1.13/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/influxdata/influxdb/query/control.(*Controller).compileQuery.func1(0xc000afa950, 0xc002d536e0)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/influxdb@v1.5.1-0.20200114154938-f3bb6ff042e8/query/control/controller.go:327 +0xfa
panic(0x1d17fe0, 0x403aa50)
	/usr/local/Cellar/go/1.13/libexec/src/runtime/panic.go:679 +0x1b2
github.com/influxdata/influxdb/query/stdlib/influxdata/influxdb.PushDownFilterRule.Rewrite(0x2fa8960, 0xc0003ff9e0, 0x2045da0, 0x6, 0xc0009ca3e0, 0x1, 0x1)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/influxdb@v1.5.1-0.20200114154938-f3bb6ff042e8/query/stdlib/influxdata/influxdb/rules.go:109 +0xed
github.com/influxdata/flux/plan.(*heuristicPlanner).matchRules(0xc00036af10, 0x2fa8960, 0xc0003ff9e0, 0x440f5a0, 0xc0003ff900, 0xc000188c00, 0x0, 0x0)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/flux@v0.58.4/plan/heuristic_planner.go:60 +0x35e
github.com/influxdata/flux/plan.(*heuristicPlanner).Plan(0xc00036af10, 0xc000a2f900, 0x0, 0x0, 0x0)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/flux@v0.58.4/plan/heuristic_planner.go:101 +0x257
github.com/influxdata/flux/plan.(*physicalPlanner).Plan(0xc000c15820, 0xc000a2f900, 0xc000a2f900, 0x0, 0x0)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/flux@v0.58.4/plan/physical.go:43 +0x3c
github.com/influxdata/flux/plan.(*planner).Plan(0xc000c15880, 0xc0003fefc0, 0x0, 0x0, 0x0)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/flux@v0.58.4/plan/builder.go:47 +0xa4
github.com/influxdata/flux/repl.Compiler.Compile(0xc0003fefc0, 0x2f73900, 0xc000ca1c50, 0x0, 0xc000afa8d0, 0xc000d9af40, 0xc000d9af40)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/flux@v0.58.4/repl/compiler.go:21 +0x67
github.com/influxdata/influxdb/query/control.(*Controller).compileQuery(0xc000286fd0, 0xc000d9af00, 0x2f344c0, 0xc00000e7d8, 0x2f1d0c0, 0x403aa50)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/influxdb@v1.5.1-0.20200114154938-f3bb6ff042e8/query/control/controller.go:341 +0x113
github.com/influxdata/influxdb/query/control.(*Controller).query(0xc000286fd0, 0x2f73900, 0xc000ca0b70, 0x2f344c0, 0xc00000e7d8, 0xc00036acb0, 0x2f73900, 0xc000ca0a20, 0x4)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/influxdb@v1.5.1-0.20200114154938-f3bb6ff042e8/query/control/controller.go:225 +0xaf
github.com/influxdata/influxdb/query/control.(*Controller).Query(0xc000286fd0, 0x2f73900, 0xc000ca0930, 0xc000749b30, 0x0, 0x0, 0x0, 0x0)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/influxdb@v1.5.1-0.20200114154938-f3bb6ff042e8/query/control/controller.go:209 +0x258
github.com/influxdata/influxdb/query.ProxyQueryServiceAsyncBridge.Query(0x2f185a0, 0xc000286fd0, 0x2f73900, 0xc000ca0930, 0x2f17480, 0xc000c15560, 0xc000749b30, 0x0, 0x0, 0x0, ...)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/influxdb@v1.5.1-0.20200114154938-f3bb6ff042e8/query/bridges.go:136 +0x134
...
```

I could reproduce also on a fresh container running `v0.57.0` by writing some points and querying with a `filter` transformation.

**Comment by wolffcm** [comment]
It must not be data-dependent, because the panic is during planning.  What was the query?

**Comment by affo** [comment]
Yeah, I think you are absolutely right, it should be something in the planner.

The query is actually super easy:

```
from(bucket: "test")
  |> range(start: -1m)
  |> filter(fn: (r) => r._measurement == "...")
```

**Comment by wolffcm** [comment]
I investigated this earlier with @affo for a bit.  He can reproduce it in his setup, which is a little unusual, of running OSS from a Docker image inside kubernetes, by querying with the REPL. (Lorenzo please correct me if I'm wrong here)

I tried to reproduce this on OSS with version 0.58.4, with both the web UI and the REPL, and I cannot.  I also tried to reproduce this in acceptance (which is also on 0.58.4 now) but everything seems to work fine there too.

**Comment by wolffcm** [comment]
Yes, I was using a REPL built from the latest bits on master.

**Comment by affo** [comment]
I verified that I was using an old version on the `influx` client.

I accidentally ran `go build` instead of `go install` so I was using the old `influx` in my `PATH` (who knows how old it was 😅 ).

I am sorry for the unnecessary noise. Thank you!
