### ISSUE TITLE
map() panics on null values in algo-w branch

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2497]
The test `TestMap_Process` panics for the subtests where input tables contain null values:
```
=== RUN   TestMap_Process/with_null_column
goroutine 345 [running]:
runtime/debug.Stack(0xc00b4cb080, 0x40, 0x40)
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/influxdata/flux/execute/executetest.ProcessTestHelper.func1(0xc00b4cc800)
	/Users/cwolff/workspace/github.com/influxdata/flux/execute/executetest/transformation.go:65 +0x57
panic(0x53d5860, 0xc00b4a0fe0)
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1b2
github.com/influxdata/flux/execute.PanicUnknownType(...)
	/Users/cwolff/workspace/github.com/influxdata/flux/execute/table.go:1217
github.com/influxdata/flux/execute.(*ColListTableBuilder).AddCol(0xc00b4bd4a0, 0xc00b4b3b85, 0x7, 0x0, 0x6f912a0, 0x1, 0x0)
	/Users/cwolff/workspace/github.com/influxdata/flux/execute/table.go:696 +0xd42
github.com/influxdata/flux/stdlib/universe.(*mapTransformation).createSchema(0xc00b4c5cc0, 0x62f7620, 0xc00b4bd4a0, 0x62f25c0, 0xc00b4bd400, 0xc00b4c7401, 0x62f1280)
	/Users/cwolff/workspace/github.com/influxdata/flux/stdlib/universe/map.go:268 +0x3cb
github.com/influxdata/flux/stdlib/universe.(*mapTransformation).Process.func1(0x62ebb40, 0xc00b4c5f80, 0x2, 0xc00b4cf2e0)
	/Users/cwolff/workspace/github.com/influxdata/flux/stdlib/universe/map.go:172 +0x4fb
github.com/influxdata/flux/execute/executetest.(*Table).Do(0xc009ad2750, 0xc00b4c73b0, 0x0, 0x0)
	/Users/cwolff/workspace/github.com/influxdata/flux/execute/executetest/table.go:181 +0x218
github.com/influxdata/flux/stdlib/universe.(*mapTransformation).Process(0xc00b4c5cc0, 0x3947de3b0a22f43e, 0xb788115da452a89b, 0x62cf560, 0xc009ad2750, 0xc00b4c5cc0, 0x119)
	/Users/cwolff/workspace/github.com/influxdata/flux/stdlib/universe/map.go:152 +0xd8
github.com/influxdata/flux/execute/executetest.ProcessTestHelper(0xc00b4cc800, 0xc009ae06f0, 0x1, 0x1, 0xc009ae2268, 0x1, 0x1, 0x0, 0x0, 0xc001678ee8)
	/Users/cwolff/workspace/github.com/influxdata/flux/execute/executetest/transformation.go:79 +0x24e
github.com/influxdata/flux/stdlib/universe_test.TestMap_Process.func2(0xc00b4cc800)
	/Users/cwolff/workspace/github.com/influxdata/flux/stdlib/universe/map_test.go:731 +0x104
testing.tRunner(0xc00b4cc800, 0xc00b4670a0)
	/usr/local/Cellar/go/1.13.3/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.3/libexec/src/testing/testing.go:960 +0x350
    --- FAIL: TestMap_Process/with_null_column (0.00s)
        transformation.go:66: caught panic: unknown type invalid
```

**Comment by wolffcm** [comment]
Failing tests are in `stdlib/universe/map_test.go`, skipped with this issue URL.
