### ISSUE TITLE
ARM : flux Error Handling issue (?)

### ISSUE THREAD

**Issue by ChitlangeSahas** [influxdata/flux#2899]
`TL;DR ` : Flux seems to have issues handling the errors on ARM. It crashes and throws a runtime stack at me and not the usual syntax error message. 

`uname - a` returns : 
`Linux raspberrypi 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux`

What I did: 

1. Open Flux REPL by `./flux repl` in the CLI
2. Type in undefined variable `> hello`

Resulting in : 

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe1a04020 pc=0xbe69c4]

runtime stack:
runtime.throw(0x105df29, 0x2a)
	/usr/local/go/src/runtime/panic.go:617 +0x5c
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x3fc

goroutine 1 [syscall]:
runtime.cgocall(0xbe3180, 0x3887b68, 0x57512c)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5c fp=0x3887b50 sp=0x3887b38 pc=0x1f1174
github.com/influxdata/flux/libflux/go/libflux._Cfunc_flux_error_str(0x629007b8, 0x0)
	_cgo_gotypes.go:161 +0x38 fp=0x3887b64 sp=0x3887b50 pc=0x5729a0
github.com/influxdata/flux/libflux/go/libflux.(*Analyzer).Analyze.func4(0x629007b8, 0x33b42c8)
	/home/builder/src/libflux/go/libflux/analyze.go:98 +0x44 fp=0x3887b7c sp=0x3887b64 pc=0x5751c8
github.com/influxdata/flux/libflux/go/libflux.(*Analyzer).Analyze(0x37375f8, 0x33b42b0, 0x0, 0x0, 0x0)
	/home/builder/src/libflux/go/libflux/analyze.go:98 +0xb4 fp=0x3887bb8 sp=0x3887b7c pc=0x573770
github.com/influxdata/flux/repl.(*REPL).analyzeLine(0x37f7f00, 0x34700b0, 0x5, 0x30545a0, 0xaa, 0x76d036cc)
	/home/builder/src/repl/repl.go:200 +0x50 fp=0x3887bd4 sp=0x3887bb8 pc=0xb1c78c
github.com/influxdata/flux/repl.(*REPL).Eval(0x37f7f00, 0x34700b0, 0x5, 0x1, 0x224828, 0x0, 0x0, 0x0)
	/home/builder/src/repl/repl.go:157 +0x40 fp=0x3887c10 sp=0x3887bd4 pc=0xb1c20c
github.com/influxdata/flux/repl.(*REPL).executeLine(0x37f7f00, 0x34700b0, 0x5, 0x0, 0xb14c1c)
	/home/builder/src/repl/repl.go:167 +0x30 fp=0x3887c9c sp=0x3887c10 pc=0xb1c378
github.com/influxdata/flux/repl.(*REPL).input(0x37f7f00, 0x34700b0, 0x5)
	/home/builder/src/repl/repl.go:139 +0x2c fp=0x3887cd0 sp=0x3887c9c pc=0xb1c130
github.com/influxdata/flux/repl.(*REPL).input-fm(0x34700b0, 0x5)
	/home/builder/src/repl/repl.go:138 +0x2c fp=0x3887ce0 sp=0x3887cd0 pc=0xb1d41c
github.com/c-bata/go-prompt.(*Prompt).Run(0x37f7f40)
	/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.2/prompt.go:81 +0x55c fp=0x3887dcc sp=0x3887ce0 pc=0xb14c40
github.com/influxdata/flux/repl.(*REPL).Run(0x37f7f00)
	/home/builder/src/repl/repl.go:80 +0x180 fp=0x3887e0c sp=0x3887dcc pc=0xb1b6f4
github.com/influxdata/flux/cmd/flux/cmd.glob..func1(0x2a0b5f8, 0x2a60630, 0x0, 0x0)
	/home/builder/src/cmd/flux/cmd/repl.go:26 +0x144 fp=0x3887e9c sp=0x3887e0c pc=0xb1dc88
github.com/spf13/cobra.(*Command).execute(0x2a0b5f8, 0x2a60630, 0x0, 0x0, 0x2a0b5f8, 0x2a60630)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x204 fp=0x3887f0c sp=0x3887e9c pc=0xb02124
github.com/spf13/cobra.(*Command).ExecuteC(0x2a0b728, 0x1, 0x1f46ca8, 0x29)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x22c fp=0x3887f70 sp=0x3887f0c pc=0xb02a74
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/influxdata/flux/cmd/flux/cmd.Execute()
	/home/builder/src/cmd/flux/cmd/root.go:20 +0x24 fp=0x3887f9c sp=0x3887f70 pc=0xb1dab8
main.main()
	/home/builder/src/cmd/flux/main.go:18 +0xbc fp=0x3887fc4 sp=0x3887f9c pc=0xb37344
runtime.main()
	/usr/local/go/src/runtime/proc.go:200 +0x204 fp=0x3887fe4 sp=0x3887fc4 pc=0x21d944
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:868 +0x4 fp=0x3887fe4 sp=0x3887fe4 pc=0x248bb8

goroutine 20 [select]:
go.opencensus.io/stats/view.(*worker).start(0x339ba00)
	/go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0xb0
created by go.opencensus.io/stats/view.init.0
	/go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x48

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x130
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x14
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x30

goroutine 9 [chan receive]:
github.com/influxdata/flux/repl.(*REPL).Run.func1(0x37f7f80, 0x37f7f00)
	/home/builder/src/repl/repl.go:76 +0x54
created by github.com/influxdata/flux/repl.(*REPL).Run
	/home/builder/src/repl/repl.go:75 +0x174 
```

Any ideas why that would happen? 

**[Update] 11 - June - 2020 :** 

I hypothesize it's an issue with Go and ARM, the `go test std` fails. 

Test Output :   [go_test_output.txt](https://github.com/influxdata/flux/files/4766824/go_test_output.txt)

**Comment by cinhcet** [comment]
not sure if this is related to your problem, but ARM and flux is not a good combination at the moment
https://github.com/influxdata/flux/issues/2505
I also compiled flux on armv7l (through compiling influxdb) and queries do not work at all

**Comment by ChitlangeSahas** [comment]
I quickly realized that! @cinhcet. The issue seems to be on the RUST side tho. I went through the code and there are some things like raw pointers being passed, magically they are being handled fine in other architectures but crash in ARM. 

If you know RUST and are willing to collaborate to solve this issue let me know  👍  I am interning with the flux team and was hoping to solve the ARM support issue, would love any insights.

**Comment by cinhcet** [comment]
I have not done anything yet with RUST, so I am probably not of much help there.

**Comment by ChitlangeSahas** [comment]
@cinhcet No worries! Let's hope for some magic haha!

**Comment by andig** [comment]
Looks to me as if there is a problem with the integration of the rust flux parser into the go runtime as the crash is inside libflux and seems to involve cgocall.
