### ISSUE TITLE
Panic when group on empty table

### ISSUE THREAD

**Issue by affo** [influxdata/flux#319]
The query:

```
from(bucket: "test")
    |> range(start: -1m)
```

returns no result.

The query:

```
from(bucket: "test")
    |> range(start: -1m)
    |> group(by: ["_measurement"])
```

Panics:

```
Error: panic: runtime error: index out of range
goroutine 1772875 [running]:
runtime/debug.Stack(0x1067e00, 0x1057520, 0x1cdac20)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do.func1.1(0xc0003dcb80)
	/root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:250 +0xbc
panic(0x1057520, 0x1cdac20)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*table).readTags(0xc003653000, 0xc001b654a0, 0x4, 0xf92)
	/root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/table.go:113 +0x228
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.newFloatGroupTable(0xc006c7bb60, 0x13565a0, 0xc0012af468, 0x7f673ec44968, 0xc001e760d8, 0x15696d22bcf54518, 0x15696d30b53c9d18, 0x135e660, 0xc0031b85d0, 0xc003b04000, ...)
	/root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/table.gen.go:131 +0x2b5
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*tableIterator).handleGroupRead(0xc004a181e0, 0xc006fdd1f0, 0x1342de0, 0xc0012af400, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/reader.go:284 +0x88b
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*tableIterator).Do(0xc004a181e0, 0xc006fdd1f0, 0xc0043f38f0, 0x133aa80)
	/root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/reader.go:109 +0x2e8
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage.(*source).run(0xc0012af2c0, 0x134e5c0, 0xc0043f38f0, 0x472e65, 0xc007a3cf80)
	/root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage/storage.go:105 +0xfb
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage.(*source).Run(0xc0012af2c0, 0x134e5c0, 0xc0043f38f0)
	/root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage/storage.go:96 +0x43
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do.func1(0xc0003dcb80, 0x134e5c0, 0xc0043f38f0, 0x1342ce0, 0xc0012af2c0)
	/root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:257 +0x6b
created by github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do
	/root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:238 +0x99
```

**Comment by affo** [comment]
From the stack trace, it seems to be a problem in `platform`, but maybe it is flux that pushes down to storage something wrong.

**Comment by zarbis** [comment]
I'm affected by this one. My query is:
```
from(bucket: "analytics") 
|> range(start: 2018-12-04T21:00:00.000Z, stop: 2018-12-05T20:59:59.999Z) 
|> filter(fn: (r) => r._measurement == "offers-profit" AND 
  r._field == "money" AND 
  r.utm_source == "direct" ) 
|> group(none: true)
```
Response is about 20 lines total, sample without time fields:
```
_value    _field    _measurement    offer    utm_campaign    utm_medium    utm_source
32.075616    money    offers-profit    foo2-9    bar2-10    cpc    direct
34.080342    money    offers-profit    foo2-9    bar3-10    cpc    direct
26.061438    money    offers-profit    foo2-9    bar4-10    cpc    direct
```
When I try to do `|> group(by: ["utm_campaign"])` in last line I get `Error: panic: runtime error: index out of range`. Grouping on any other tag works fine.

```
Error: panic: runtime error: index out of range
goroutine 38072718 [running]:
runtime/debug.Stack(0x105eac0, 0x104e260, 0x1cc88b0)
    /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do.func1.1(0xc01ba2ae00)
    /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:250 +0xbc
panic(0x104e260, 0x1cc88b0)
    /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*table).readTags(0xc01e9a2d00, 0xc0212c9520, 0x6, 0xe3a)
    /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/table.go:113 +0x228
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.newFloatGroupTable(0xc01eb74540, 0x134bc60, 0xc004994ba8, 0x7fa541828c00, 0xc00d4e9c58, 0x156d3ce4a6682000, 0x156d8b7937a7ddc0, 0x1353d20, 0xc019e05380, 0xc01b9c2540, ...)
    /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/table.gen.go:131 +0x2b5
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*tableIterator).handleGroupRead(0xc0159902d0, 0xc02182c4f0, 0x1338540, 0xc004994b40, 0x0, 0x0)
    /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/reader.go:284 +0x88b
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*tableIterator).Do(0xc0159902d0, 0xc02182c4f0, 0xc01f767b90, 0x1330200)
    /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/reader.go:109 +0x2e8
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage.(*source).run(0xc004994780, 0x1343c80, 0xc01f767b90, 0x0, 0xc01df84780)
    /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage/storage.go:105 +0xfb
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage.(*source).Run(0xc004994780, 0x1343c80, 0xc01f767b90)
    /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage/storage.go:96 +0x43
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do.func1(0xc01ba2ae00, 0x1343c80, 0xc01f767b90, 0x1338440, 0xc004994780)
    /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:257 +0x6b
created by github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do
    /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:238 +0x99
```

**Comment by affo** [comment]
Hello, can you `yield` the result before the group?

```
from(bucket: "analytics") 
|> range(start: 2018-12-04T21:00:00.000Z, stop: 2018-12-05T20:59:59.999Z) 
|> filter(fn: (r) => r._measurement == "offers-profit" AND 
  r._field == "money" AND 
  r.utm_source == "direct" ) 
|> yield(name: "before_group")
|> group(none: true)
```

Let's see if it is because of empty tables or mixed types.

**Comment by zarbis** [comment]
@affo Yes, there is a lot of empty tables with current time.

**Comment by affo** [comment]
Yeah, we need to fix this. Thank you.

**Comment by wolffcm** [comment]
Several reproducers here in this thread, here's what did it for me:
```
from(bucket: "telegraf")
|> range(start: -1s)
|> filter(fn: (r) => r._measurement == "disk" and r._field == "used")
|> group(columns: ["path"])
```

When the range is small, like above, I get the panic.  When I increase the range such that there is data to be grouped, the query works.

This seems to happen because we don't find a key column in the set of tags:
https://github.com/influxdata/platform/blob/master/storage/reads/table.go#L116

At line 116 `j` is set to `-1` because there is no column called `_field` in `t.cols`.

@nathanielc @stuartcarnie Since this seems to be an issue in the `platform/storage/reads` package, should this be put on the storage backlog?  I'm a little unclear on who should fix this one.

**Comment by aanthony1243** [comment]
@stuartcarnie  I didn't go all the way up the stack, but I think the turning point for this bug is here: 

https://github.com/influxdata/platform/blob/1862b4421df347adaf9e4a91cda57f22a5a65fbc/storage/reads/reader.go#L220

looks like that call is getting a list of keys that are then not on the table, causing the crash at https://github.com/influxdata/platform/blob/master/storage/reads/table.go#L116
