### ISSUE TITLE
Panic when pivoting

### ISSUE THREAD

**Issue by affo** [influxdata/flux#337]
Panicked when streaming logs:

```
ERROR: panic: column facility_code is not of type string
goroutine 30330 [running]:
runtime/debug.Stack(0x1068020, 0x10391c0, 0xc01ab60890)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc01083aa80)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:73 +0xbc
panic(0x10391c0, 0xc01ab60890)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.CheckColType(0xc007ebbf80, 0xd, 0x2, 0x5)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/table.go:935 +0xff
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.ColListTableBuilder.checkCol(0xc00a8b6af0, 0xc00ce840a0, 0xa, 0x5, 0x40, 0xc000582280)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/table.go:929 +0x104
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.ColListTableBuilder.GrowStrings(0xc00a8b6af0, 0xc00ce840a0, 0xa, 0x1, 0xffffffffffffffff, 0x0)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/table.go:841 +0x4c
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations.growColumn(0x1366a40, 0xc006351fc0, 0x5, 0xa, 0x1, 0x3d, 0xb)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations/pivot.go:333 +0x267
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations.(*pivotTransformation).Process.func1(0x135aa60, 0xc00615f860, 0xc00615f860, 0x11a4501)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations/pivot.go:298 +0x71e
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*stringTable).Do(0xc00615f860, 0xc00cacbb80, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/table.gen.go:687 +0x94
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations.(*pivotTransformation).Process(0xc00bc22b80, 0xb2533050b9d247a4, 0x36a2feffbffb91b5, 0x7fb7c0191cc8, 0xc00615f860, 0xde01, 0xc0006cec00)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations/pivot.go:252 +0xa53
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.processMessage(0x1352ca0, 0xc00bc22b80, 0x1341040, 0xc00506bd20, 0xc00f5bbf40, 0x5edf6d, 0xc00a94eb90)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:199 +0x1fc
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc01083aae0, 0xa)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:156 +0xa1
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages-fm(0xa)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:137 +0x34
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc01083aa80, 0x134e9a0, 0xc00968c8a0)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:126 +0x4b
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc01083aa80, 0x134e9a0, 0xc00968c8a0)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:80 +0x95
created by github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).Start
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:61 +0x7e
```

**Comment by wolffcm** [comment]
@affo Do you have a query or steps to reproduce for this one?

**Comment by affo** [comment]
It didn't happen to me unfortunately, but it was produced by the `dump` command: https://github.com/influxdata/inflummoxed/blob/la-flux-logs/dump/log-querier.go#L63 (the query is in the code).

**Comment by wolffcm** [comment]
I wonder if this is related to:
https://github.com/influxdata/platform/issues/47

**Comment by affo** [comment]
Yeah, could be. I'll work on this today and try to reproduce it and chase it.

**Comment by affo** [comment]
Couldn't actually reproduce it. I don't know what went wrong in that specific case.

**Comment by jsternberg** [comment]
I am going to clarify the error message to include the real column type so the error message can be more helpful and then I will put this back on the backlog.
