### ISSUE TITLE
Different `from` calls place results in same table

### ISSUE THREAD

**Issue by chnn** [influxdata/flux#398]
I'm running the following query (auto generated, hence the repetition):

```
from(bucket: "telegraf")
  |> range(start: -24h)
  |> filter(fn: (r) => r._measurement == "mem")
  |> filter(fn: (r) => r._field == "active")
  |> window(every: 20m)
  |> max()
  |> group(columns: ["_value", "_time", "_start", "_stop"], mode: "except")
  |> yield(name: "max")

from(bucket: "telegraf")
  |> range(start: -24h)
  |> filter(fn: (r) => r._measurement == "mem")
  |> filter(fn: (r) => r._field == "active")
  |> window(every: 20m)
  |> min()
  |> group(columns: ["_value", "_time", "_start", "_stop"], mode: "except")
  |> yield(name: "min")
```

I get results that look like:
```
#group,false,false,false,false,false,false,true,true,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string
#default,max,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,host
,,0,2018-12-05T23:53:17.127826Z,2018-12-06T00:00:00Z,2018-12-05T23:58:08Z,6765428736,active,mem,oox4k.local
,,0,2018-12-06T00:00:00Z,2018-12-06T00:20:00Z,2018-12-06T00:02:59Z,6651666432,active,mem,oox4k.local
,,0,2018-12-06T00:20:00Z,2018-12-06T00:40:00Z,2018-12-06T00:32:14Z,6356340736,active,mem,oox4k.local
,,0,2018-12-06T00:40:00Z,2018-12-06T01:00:00Z,2018-12-06T00:46:22Z,6639796224,active,mem,oox4k.local

<snip>

#group,false,false,false,false,false,false,true,true,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string
#default,min,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,host
,,0,2018-12-05T23:53:17.127826Z,2018-12-06T00:00:00Z,2018-12-05T23:55:08Z,6069874688,active,mem,oox4k.local
,,0,2018-12-06T00:00:00Z,2018-12-06T00:20:00Z,2018-12-06T00:03:39Z,6054170624,active,mem,oox4k.local
,,0,2018-12-06T00:20:00Z,2018-12-06T00:40:00Z,2018-12-06T00:32:24Z,6216536064,active,mem,oox4k.local
,,0,2018-12-06T00:40:00Z,2018-12-06T01:00:00Z,2018-12-06T00:44:42Z,5993914368,active,mem,oox4k.local

<snip>

```
I was surprised to see that both results had the same table ID. Is this expected behavior? If so, is the yield name the only way to distinguish between the results?

I also ran into a panic if I left off the `yield` calls:

```
goroutine 25303 [running]:
net/http.(*conn).serve.func1(0xc000e863c0)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1746 +0xd0
panic(0x1e43e00, 0x2c48690)
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/flux.(*queryResultIterator).Statistics(0xc002cf71d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/chris/Dev/Go/pkg/mod/github.com/influxdata/flux@v0.7.2/result_iterator.go:77 +0x9d
github.com/influxdata/platform/query.ProxyQueryServiceBridge.Query(0x21db100, 0xc001827050, 0x21ed100, 0xc00169ce40, 0x6111530, 0xc000f8c5a0, 0xc002c6c780, 0x0, 0x0, 0x0)
	/Users/chris/Dev/Go/src/github.com/influxdata/platform/query/bridges.go:54 +0x23e
github.com/influxdata/platform/http.(*FluxHandler).handlePostQuery(0xc000011b80, 0x21e8340, 0xc000f8c5a0, 0xc000114f00)
	/Users/chris/Dev/Go/src/github.com/influxdata/platform/http/query_handler.go:82 +0x314
github.com/influxdata/platform/http.(*FluxHandler).handlePostQuery-fm(0x21e8340, 0xc000f8c5a0, 0xc000114f00)
	/Users/chris/Dev/Go/src/github.com/influxdata/platform/http/query_handler.go:51 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0003289c0, 0x21e8340, 0xc000f8c5a0, 0xc000114f00)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964 +0x44
github.com/julienschmidt/httprouter.(*Router).Handler.func1(0x21e8340, 0xc000f8c5a0, 0xc000114e00, 0x0, 0x0, 0x0)
	/Users/chris/Dev/Go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/params_go17.go:26 +0x1c7
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000011b40, 0x21e8340, 0xc000f8c5a0, 0xc000114e00)
	/Users/chris/Dev/Go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x792
github.com/influxdata/platform/http.(*APIHandler).ServeHTTP(0xc00302c000, 0x21e8340, 0xc000f8c5a0, 0xc000114e00)
	/Users/chris/Dev/Go/src/github.com/influxdata/platform/http/api_handler.go:207 +0x80f
github.com/influxdata/platform/http.(*AuthenticationHandler).ServeHTTP(0xc000010ac0, 0x21e8340, 0xc000f8c5a0, 0xc000114c00)
	/Users/chris/Dev/Go/src/github.com/influxdata/platform/http/authentication_middleware.go:98 +0x384
github.com/influxdata/platform/http.(*PlatformHandler).ServeHTTP(0xc00476c820, 0x21e8340, 0xc000f8c5a0, 0xc000114c00)
	/Users/chris/Dev/Go/src/github.com/influxdata/platform/http/platform_handler.go:59 +0xb5
github.com/influxdata/platform/http.(*Handler).ServeHTTP(0xc000bc0240, 0x21eb2c0, 0xc000ac4540, 0xc000114c00)
	/Users/chris/Dev/Go/src/github.com/influxdata/platform/http/handler.go:166 +0x21a
net/http.serverHandler.ServeHTTP(0xc00028c410, 0x21eb2c0, 0xc000ac4540, 0xc003baa400)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000e863c0, 0x21ed040, 0xc00462a3c0)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2851 +0x2f5
```

**Comment by nathanielc** [comment]
@chnn Yes this is expected, table IDs are unique within a single result. 

The panic is not expected and we will fix that.

**Comment by chnn** [comment]
Ok, thanks!

**Comment by nathanielc** [comment]
This panic should be fixed.
