### ISSUE TITLE
Union a single data set to each group key in a data set - internal error: panic: arrow/array: index out of range

### ISSUE THREAD

**Issue by jonathandavis805** [influxdata/flux#5265]
Flux Query as suggested

```
mapped_state_changes = state_changes
  |> set(key: "on", value: "x")

mapped_last_value_per_id = last_value_per_id
  |> set(key: "on", value: "x")

join.inner(left: mapped_last_value_per_id,  right: mapped_state_changes,  on: (l, r) => l.on == r.on,  as: (l, r) => { return {r with id: l.id} } )
```

Flux returns the error `internal error: panic: arrow/array: index out of range`

Data:

Data to union - state_changes
_start | _stop | _time | bool_value
-- | -- | -- | --
2022-09-14 12:24:30 | 2022-09-28 12:24:30 | 2022-09-28 12:24:30 | TRUE
2022-09-28 12:24:30 | 2022-10-05 12:24:30 | 2022-09-28 17:00:00 | FALSE
2022-09-28 12:24:30 | 2022-10-05 12:24:30 | 2022-09-29 7:00:00 | TRUE
2022-09-28 12:24:30 | 2022-10-05 12:24:30 | 2022-09-29 17:00:00 | FALSE
2022-09-28 12:24:30 | 2022-10-05 12:24:30 | 2022-09-30 8:00:00 | TRUE
2022-09-28 12:24:30 | 2022-10-05 12:24:30 | 2022-09-30 16:00:00 | FALSE
2022-09-28 12:24:30 | 2022-10-05 12:24:30 | 2022-10-03 7:00:00 | TRUE
2022-09-28 12:24:30 | 2022-10-05 12:24:30 | 2022-10-03 17:00:00 | FALSE
2022-09-28 12:24:30 | 2022-10-05 12:24:30 | 2022-10-04 7:00:00 | TRUE
2022-09-28 12:24:30 | 2022-10-05 12:24:30 | 2022-10-04 17:00:00 | FALSE
2022-09-28 12:24:30 | 2022-10-05 12:24:30 | 2022-10-05 7:00:00 | TRUE
2022-09-28 12:24:30 | 2022-10-05 12:24:30 | 2022-10-05 12:24:30 | TRUE
2022-09-14 12:24:30 | 2022-09-28 12:24:30 | 2022-10-05 12:24:30 | TRUE

Grouped Data - last_value_per_id
_start | _stop | _time | _value | id
-- | -- | -- | -- | --
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-10-05 10:26:38 | complete | 2cbuegt
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-28 13:57:12 | complete | 2mmm4ty
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-28 13:57:24 | complete | 2phukx1
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-28 13:57:27 | complete | 2phumdg
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-28 13:57:39 | complete | 2phumf9
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-28 13:57:41 | complete | 2phumga
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-28 13:57:44 | complete | 2phumhb
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-28 13:57:47 | complete | 2phumy4
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-29 6:35:08 | complete | 2rpktzp
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-29 6:35:26 | in process | 2rpku22
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-28 13:01:45 | print parts | 2rppefg
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-28 15:42:52 | active | 2tk4dyq
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-29 10:47:35 | complete | 2vjwujg
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-30 10:54:23 | complete | 2vjyk95
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-10-04 15:43:50 | complete | 2vk21ev
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-10-05 8:43:58 | complete | 2vk2br3
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-10-05 8:44:07 | complete | 2vk2mjk
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-10-05 8:44:29 | complete | 2vk3ahj
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-10-05 8:44:20 | complete | 2vk3py1
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-29 13:53:56 | complete | 2vk3rmj
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-10-03 15:12:30 | complete | 2vrhtmg
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-10-05 8:44:36 | complete | 2vrhxh8
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-28 15:57:40 | complete | 2vrj84u
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-29 14:24:25 | complete | 2vrj8nu
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-09-29 14:27:06 | complete | 2vrna6z
2022-09-28 12:24:57 | 2022-10-05 12:24:57 | 2022-10-04 9:56:55 | complete | 2vrnv3j

Details: OS: Amazon/Linux in AWS EKS
Version: 0.179.0
Installed via Docker Image of Influx DB 2.4 alpine

**Comment by jonathandavis805** [comment]
for reference https://influxcommunity.slack.com/archives/CH8RGRW4T/p1664984404046529

**Comment by nathanielc** [comment]
I created this script to test it:

```
import "internal/debug"
import "array"
import "join"

stateChanges =
    array.from(
        rows: [
            {_time: 2022-09-28T12:24:30Z, bool_value: true},
            {_time: 2022-09-28T17:00:00Z, bool_value: false},
            {_time: 2022-09-29T07:00:00Z, bool_value: true},
            {_time: 2022-09-29T17:00:00Z, bool_value: false},
            {_time: 2022-09-30T08:00:00Z, bool_value: true},
            {_time: 2022-09-30T16:00:00Z, bool_value: false},
            {_time: 2022-10-03T07:00:00Z, bool_value: true},
            {_time: 2022-10-03T17:00:00Z, bool_value: false},
            {_time: 2022-10-04T07:00:00Z, bool_value: true},
            {_time: 2022-10-04T17:00:00Z, bool_value: false},
            {_time: 2022-10-05T07:00:00Z, bool_value: true},
            {_time: 2022-10-05T12:24:30Z, bool_value: true},
            {_time: 2022-10-05T12:24:30Z, bool_value: true},
        ],
    )
        |> debug.opaque()
lastValuePerId =
    array.from(
        rows: [
            {_time: 2022-10-05T10:26:38Z, _value: "complete", id: "2cbuegt"},
            {_time: 2022-09-28T13:57:12Z, _value: "complete", id: "2mmm4ty"},
            {_time: 2022-09-28T13:57:24Z, _value: "complete", id: "2phukx1"},
            {_time: 2022-09-28T13:57:27Z, _value: "complete", id: "2phumdg"},
            {_time: 2022-09-28T13:57:39Z, _value: "complete", id: "2phumf9"},
            {_time: 2022-09-28T13:57:41Z, _value: "complete", id: "2phumga"},
            {_time: 2022-09-28T13:57:44Z, _value: "complete", id: "2phumhb"},
            {_time: 2022-09-28T13:57:47Z, _value: "complete", id: "2phumy4"},
            {_time: 2022-09-29T06:35:08Z, _value: "complete", id: "2rpktzp"},
            {_time: 2022-09-29T06:35:26Z, _value: "in process", id: "2rpku22"},
            {_time: 2022-09-28T13:01:45Z, _value: "print parts", id: "2rppefg"},
            {_time: 2022-09-28T15:42:52Z, _value: "active", id: "2tk4dyq"},
            {_time: 2022-09-29T10:47:35Z, _value: "complete", id: "2vjwujg"},
            {_time: 2022-09-30T10:54:23Z, _value: "complete", id: "2vjyk95"},
            {_time: 2022-10-04T15:43:50Z, _value: "complete", id: "2vk21ev"},
            {_time: 2022-10-05T08:43:58Z, _value: "complete", id: "2vk2br3"},
            {_time: 2022-10-05T08:44:07Z, _value: "complete", id: "2vk2mjk"},
            {_time: 2022-10-05T08:44:29Z, _value: "complete", id: "2vk3ahj"},
            {_time: 2022-10-05T08:44:20Z, _value: "complete", id: "2vk3py1"},
            {_time: 2022-09-29T13:53:56Z, _value: "complete", id: "2vk3rmj"},
            {_time: 2022-10-03T15:12:30Z, _value: "complete", id: "2vrhtmg"},
            {_time: 2022-10-05T08:44:36Z, _value: "complete", id: "2vrhxh8"},
            {_time: 2022-09-28T15:57:40Z, _value: "complete", id: "2vrj84u"},
            {_time: 2022-09-29T14:24:25Z, _value: "complete", id: "2vrj8nu"},
            {_time: 2022-09-29T14:27:06Z, _value: "complete", id: "2vrna6z"},
            {_time: 2022-10-04T09:56:55Z, _value: "complete", id: "2vrnv3j"},
        ],
    )
        |> debug.opaque()

mappedStateChanges =
    stateChanges
        |> set(key: "on", value: "x")

mappedLastValuePerId =
    lastValuePerId
        |> set(key: "on", value: "x")

join.inner(
    left: mappedLastValuePerId,
    right: mappedStateChanges,
    on: (l, r) => l.on == r.on,
    as: (l, r) => {
        return {r with id: l.id}
    },
)
```

However I don't get the panic. I did find a small typo in the original query, the mapped last value wasn't used as `left` to join inner.

**Comment by jonathandavis805** [comment]
Here's the error from the logs

lvl=info msg="Dispatcher panic" log_id=0dEo2Vsl000 service=storage-reads component=dispatcher error="panic: arrow/array: index out of range" stacktrace="goroutine 59970399 [running]:\nruntime/debug.Stack()\n\t/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/influxdata/flux/execute.(*poolDispatcher).recover(0xc007525ea0)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/recover.go:53 +0x205\npanic({0x7f99ebe5bf20, 0x7f99ec2c4ed8})\n\t/go/src/runtime/panic.go:838 +0x207\ngithub.com/apache/arrow/go/v7/arrow/array.NewSliceData({0x7f99ec2f9108, 0xc00d36bce0}, 0x7d0, 0xbb8)\n\t/go/pkg/mod/github.com/apache/arrow/go/v7@v7.0.0/arrow/array/data.go:154 +0x318\ngithub.com/apache/arrow/go/v7/arrow/array.NewSlice({0x7f99ec2fa8d8?, 0xc004179fc0?}, 0xc004179fc0?, 0xc00418c1c0?)\n\t/go/pkg/mod/github.com/apache/arrow/go/v7@v7.0.0/arrow/array/array.go:143 +0x45\ngithub.com/influxdata/flux/array.Slice({0x7f99ec2f5e78?, 0xc004179fc0}, 0xc00d36be00?, 0xc00273af40?)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/array/array.go:207 +0x79\ngithub.com/influxdata/flux/arrow.Slice(...)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/arrow/utils.go:130\ngithub.com/influxdata/flux/stdlib/join.getChunkSlice({{{0x7f99ec2fd278, 0xc002eebf90}, {0xc00d36bb60, 0x4, 0x4}, {0xc004179f80, 0x4, 0x4}}}, 0x1?, 0xbb8)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/join/merge_join.go:553 +0x445\ngithub.com/influxdata/flux/stdlib/join.splitChunk({{{0x7f99ec2fd278, 0xc002eebf90}, {0xc00d36bb60, 0x4, 0x4}, {0xc004179f80, 0x4, 0x4}}})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/join/join_fn.go:332 +0x236\ngithub.com/influxdata/flux/stdlib/join.(*JoinFn).Eval(0xc00273b640, {0x7f99ec2e5e28, 0xc006289640}, 0xc00273b688, {0xc00184c177, 0x5}, {0x7f99ec2e6d78, 0xc00c274a50})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/join/join_fn.go:118 +0x78a\ngithub.com/influxdata/flux/stdlib/join.(*joinProduct).evaluate(...)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/join/merge_join.go:626\ngithub.com/influxdata/flux/stdlib/join.(*joinState).join(0xc006ac03c0, {0x7f99ec2e5e28, 0xc006289640}, {0xc00184c177, 0x5}, 0xc00c392dc0, 0x0, {0x7f99ec2e6d78, 0xc00c274a50}, {0xc00d36b740, ...}, ...)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/join/merge_join.go:427 +0x2f7\ngithub.com/influxdata/flux/stdlib/join.(*MergeJoinTransformation).flush(0xc007e00cc0, 0xc006ac03c0)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/join/merge_join.go:253 +0x15b\ngithub.com/influxdata/flux/stdlib/join.(*MergeJoinTransformation).ProcessMessage(0xc007e00cc0, {0x7f99ec2e6b80?, 0xc00156a320})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/join/merge_join.go:105 +0x4dc\ngithub.com/influxdata/flux/execute.(*transportTransformationAdapter).flushKey(...)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/transport.go:770\ngithub.com/influxdata/flux/execute.(*transportTransformationAdapter).Process(0xc0076c9de0, {0x54, 0xf9, 0x10, 0x12, 0x10, 0x6d, 0x54, 0xf2, 0xab, ...}, ...)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/transport.go:754 +0x464\ngithub.com/influxdata/flux/execute.(*transportTransformationAdapter).ProcessMessage(0xc0076c9de0, {0x7f99ec2e6bf0?, 0xc00156a180})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/transport.go:727 +0x13e\ngithub.com/influxdata/flux/execute.(*consecutiveTransport).processMessage(0xc004c67e00, {0x7f99ec2e6bf0, 0xc00156a180})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/transport.go:297 +0xca\ngithub.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc004c67e00, {0x7f99ec2e5e28?, 0xc006289640?}, 0xa)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/transport.go:251 +0xe5\ngithub.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc007525ea0, {0x7f99ec2e5e28, 0xc006289640})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/dispatcher.go:157 +0x19f\ngithub.com/influxdata/flux/execute.(*poolDispatcher).run(0xc007525ea0, {0x7f99ec2e5e28, 0xc006289640})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/dispatcher.go:135 +0x4f\ngithub.com/influxdata/flux/execute.(*poolDispatcher).Start.func1()\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/dispatcher.go:75 +0x86\ncreated by github.com/influxdata/flux/execute.(*poolDispatcher).Start\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/dispatcher.go:71 +0x48\n"
