### ISSUE TITLE
internal error: panic: arrow/array: index out of range when joining a long table with another one

### ISSUE THREAD

**Issue by MarcoPignati** [influxdata/flux#5402]
Hello, with the new join functions, when my `data` table is too long, I get `internal error: panic: arrow/array: index out of range`. It is sufficient to have a too small v.windowPeriod to create the issue. I am joining a small "metadata" table (called `association`) with a timeseries table (called `data`).

I strongly suspect the issue fixed [here](https://github.com/influxdata/flux/pull/5303) is still present. I saw also other people [reporting a similar issue](https://community.influxdata.com/t/limit-on-join-function/27616) in December, so after the fix was released.

Below you see the logs when the panic appears.

I recently updated to 2.6.1, with flux 0.191.
I tried using the deprecated join() function and that one works well.

```
import "experimental"
import "regexp"
import "sql"
import "join"

data = from(bucket: "${bucket}")
|> range(start: ${__from:date}, stop: ${__to:date})
|> filter(fn: (r) => r["_measurement"] == "EstimatedVoltage")
|> filter(fn: (r) => r["_field"] == "mag")
|> filter(fn: (r) => r.UID =~ /\b${nodes:regex}\b/)
|> aggregateWindow(every: v.windowPeriod, fn: first, createEmpty: false, timeSrc: "_time")
|> drop(columns:["_start", "_stop", "_measurement", "_field"])
//|> yield(name:"data")

association = sql.from(
  driverName: "postgres",
  dataSourceName: "postgresql://${user}:${pwd}@localhost/${db}?sslmode=require",
  query: "SELECT DISTINCT ON(list.tn) tn, list.name FROM (
  SELECT concat_ws('.', l.substationname,l.conductingequipmentname) as name , t.topologicalnodeuid tn FROM location l
  INNER JOIN topology t ON l.terminaluid = t.terminaluid
  WHERE l.conductingequipmenttype = 'BusbarSection'
  AND l.substationname IN (${ss_name:sqlstring})
  AND t.topologicalnodeuid IN (${nodes:sqlstring})
  AND periods.overlaps (t.tstart,t.tend,'${__from:date}','${__to:date}')
  ) AS list;"
)
//|> rename(columns:{tn: "UID"})
//|> yield(name:"association")

out = join.left(
    left: data |> group(),
    right: association,
    on: (l, r) => l.UID == r.tn,
    as: (l, r) => ({l with name: r.name}),
)
//join(tables: {t1: data, t2: association}, on: ["UID"])
|> drop(columns: ["UID"])
|> group(columns: ["name","phase"])
|> yield(name:"result")
```
the logs returns
```
 ts=2023-03-28T07:05:55.033421Z lvl=info msg="Dispatcher panic" log_id=0gqlO58G000 service=storage-reads component=dispatcher error="panic: arrow/array: index out of range" stacktrace="goroutine 2045 [running]:
runtime/debug.Stack()
\t/go/src/runtime/debug/stack.go:24 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).recover(0xc004df6070)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/recover.go:53 +0x205
panic({0x7fd14f6668a0, 0x7fd14faed228})
\t/go/src/runtime/panic.go:838 +0x207
github.com/apache/arrow/go/v7/arrow/array.NewSliceData({0x7fd14fb24b18, 0xc00cf0cba0}, 0x7d0, 0x3e8)
\t/go/pkg/mod/github.com/apache/arrow/go/v7@v7.0.1/arrow/array/data.go:154 +0x318
github.com/apache/arrow/go/v7/arrow/array.NewSlice({0x7fd14fb26588?, 0xc00762b240?}, 0xc00762b240?, 0xc00760be50?)
\t/go/pkg/mod/github.com/apache/arrow/go/v7@v7.0.1/arrow/array/array.go:143 +0x45
github.com/influxdata/flux/array.Slice({0x7fd14fb24bd8?, 0xc00762b240}, 0x203003?, 0xc00cf0ccc0?)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/array/array.go:216 +0x79
github.com/influxdata/flux/arrow.Slice(...)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/arrow/utils.go:130
github.com/influxdata/flux/stdlib/join.getChunkSlice({{{0x7fd14fb28f28, 0xc00477fef0}, {0xc00d0fac80, 0x5, 0x5}, {0xc00760bd60, 0x5, 0x5}}}, 0xc00760bc20?, 0x3e8)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/stdlib/join/merge_join.go:553 +0x445
github.com/influxdata/flux/stdlib/join.splitChunk({{{0x7fd14fb28f28, 0xc00477fef0}, {0xc00d0fac80, 0x5, 0x5}, {0xc00760bd60, 0x5, 0x5}}})
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/stdlib/join/join_fn.go:347 +0x265
github.com/influxdata/flux/stdlib/join.(*JoinFn).Eval(0xc002a56ee8, {0x7fd14fb11830, 0xc00d08b8c0}, 0xc002a56f30, {0xc001784fb8, 0x4}, {0x7fd14fb12780, 0xc001b32460})
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/stdlib/join/join_fn.go:119 +0x78a
github.com/influxdata/flux/stdlib/join.(*joinProduct).evaluate(...)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/stdlib/join/merge_join.go:626
github.com/influxdata/flux/stdlib/join.(*joinState).join(0xc009d6c640, {0x7fd14fb11830, 0xc00d08b8c0}, {0xc001784fb8, 0x4}, 0xc000143900, 0x0, {0x7fd14fb12780, 0xc001b32460}, {0xc00ce03020, ...}, ...)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/stdlib/join/merge_join.go:427 +0x2f7
github.com/influxdata/flux/stdlib/join.(*MergeJoinTransformation).mergeJoin(0xc00a730fc0, {{{0x7fd14fb28f28, 0xc0019c4280}, {0xc009804e10, 0x2, 0x2}, {0xc000ed8680, 0x2, 0x2}}}, 0xc009d6c640, ...)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/stdlib/join/merge_join.go:219 +0x1c5
github.com/influxdata/flux/stdlib/join.(*MergeJoinTransformation).processChunk(0xc00a730fc0, {{{0x7fd14fb28f28, 0xc0019c4280}, {0xc009804e10, 0x2, 0x2}, {0xc000ed8680, 0x2, 0x2}}}, {0x7fd14f8078e0, ...}, ...)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/stdlib/join/merge_join.go:177 +0x590
github.com/influxdata/flux/stdlib/join.(*MergeJoinTransformation).ProcessMessage(0xc00a730fc0, {0x7fd14fb125c0?, 0xc00cf0c660})
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/stdlib/join/merge_join.go:86 +0x2d6
github.com/influxdata/flux/execute.(*transportTransformationAdapter).processChunk(...)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/transport.go:762
github.com/influxdata/flux/execute.(*transportTransformationAdapter).Process.func1({0x7fd14fb27020?, 0xc00ebac6c0?})
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/transport.go:749 +0x275
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do.func1({0x7fd14fb27020, 0xc00ebac6c0})
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/transport.go:572 +0x489
github.com/influxdata/flux/execute/table.(*BufferedTable).Do(0x7fd14f8731c0?, 0xc00aac76e0)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/table/buffered.go:69 +0x19b
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do(0xc00aac7638, 0xc000ed8620)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/transport.go:554 +0x87
github.com/influxdata/flux/execute.(*transportTransformationAdapter).Process(0xc0055bda10, {0x97, 0x5a, 0xdc, 0xde, 0xac, 0x9b, 0x53, 0x64, 0xb8, ...}, ...)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/transport.go:746 +0x390
github.com/influxdata/flux/execute.(*transportTransformationAdapter).ProcessMessage(0xc0055bda10, {0x7fd14fb125f8?, 0xc00087cf80})
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/transport.go:727 +0x13e
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessage(0xc0028cec30, {0x7fd14fb125f8, 0xc00087cf80})
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/transport.go:297 +0xca
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc0028cec30, {0x7fd14fb11830?, 0xc00d08b8c0?}, 0xa)
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/transport.go:251 +0xe5
github.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc004df6070, {0x7fd14fb11830, 0xc00d08b8c0})
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/dispatcher.go:157 +0x19f
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc004df6070, {0x7fd14fb11830, 0xc00d08b8c0})
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/dispatcher.go:135 +0x4f
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1()
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/dispatcher.go:75 +0x86
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
\t/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/dispatcher.go:71 +0x48
"
```

**Comment by MarcoPignati** [comment]
Still relevant

**Comment by cesuper** [comment]
Absolutely relevant. Here is my thread: https://community.influxdata.com/t/panic-arrow-array-index-out-of-range/30514
