### ISSUE TITLE
Parser panic with malformed query 

### ISSUE THREAD

**Issue by desa** [influxdata/flux#557]
Code to reproduce:

```go
package main

import (
	"github.com/influxdata/flux/parser"
)

func main() {
	parser.NewAST(`b = j |> pivot(rowKey:["_time"], colKey:["_measurement","host","cpu","y__field","x__field`)
}
```

Panic

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/influxdata/flux/internal/parser.(*parser).sourceLocation(0xc0000841e0, 0x1, 0xa, 0x1, 0x2, 0x21)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:1120 +0x226
github.com/influxdata/flux/internal/parser.(*parser).parseCallExpression(0xc0000841e0, 0x114a1e0, 0xc00000a0c0, 0x1209e08, 0x1)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:651 +0x154
github.com/influxdata/flux/internal/parser.(*parser).parsePostfixOperator(0xc0000841e0, 0xc00008da20, 0xc00000a0c0)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:623 +0x13d
github.com/influxdata/flux/internal/parser.(*parser).parsePostfixExpression(0xc0000841e0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:605 +0x57
github.com/influxdata/flux/internal/parser.(*parser).parseUnaryExpression(0xc0000841e0, 0x128e001, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:586 +0x1c4
github.com/influxdata/flux/internal/parser.(*parser).parsePipeExpressionSuffix.func1(0xc00000a0a0)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:550 +0x58
github.com/influxdata/flux/internal/parser.(*parser).repeat(0xc0000841e0, 0xc00000a0a0)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:1080 +0x27
github.com/influxdata/flux/internal/parser.(*parser).parsePipeExpression(0xc0000841e0, 0xc00000e2a0, 0xc000074b01)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:540 +0x93
github.com/influxdata/flux/internal/parser.(*parser).parseAdditiveExpression(0xc0000841e0, 0xc00000e290, 0x1)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:501 +0x49
github.com/influxdata/flux/internal/parser.(*parser).parseMultiplicativeExpression(0xc0000841e0, 0xc00000e280, 0x1209e4a)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:463 +0x49
github.com/influxdata/flux/internal/parser.(*parser).parseComparisonExpression(0xc0000841e0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:407 +0x49
github.com/influxdata/flux/internal/parser.(*parser).parseUnaryLogicalExpression(0xc0000841e0, 0xc00000e270, 0xc000074cd0)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:393 +0x1c4
github.com/influxdata/flux/internal/parser.(*parser).parseLogicalExpression(0xc0000841e0, 0x1209e1d, 0x1)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:341 +0x49
github.com/influxdata/flux/internal/parser.(*parser).parseExpression(0xc0000841e0, 0x1f, 0x3)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:307 +0x2b
github.com/influxdata/flux/internal/parser.(*parser).parseAssignStatement(0xc0000841e0, 0x3, 0x1f)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:268 +0x42
github.com/influxdata/flux/internal/parser.(*parser).parseIdentStatement(0xc0000841e0, 0x1, 0xb)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:246 +0x78
github.com/influxdata/flux/internal/parser.(*parser).parseStatement(0xc0000841e0, 0x1, 0xb)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:166 +0x112
github.com/influxdata/flux/internal/parser.(*parser).parseStatementList(0xc0000841e0, 0x1, 0x0, 0x0, 0x1)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:156 +0x7a
github.com/influxdata/flux/internal/parser.(*parser).parseProgram(0xc0000841e0, 0xc0000841e0)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:97 +0x15d
github.com/influxdata/flux/internal/parser.NewAST(0xc000062060, 0x59, 0x60, 0xc000062060)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/internal/parser/parser.go:42 +0x188
github.com/influxdata/flux/parser.NewAST(0x1134609, 0x59, 0x0, 0xc000074f88, 0xc000062058)
	/Users/michaeldesa/go/src/github.com/influxdata/flux/parser/parser.go:10 +0x60
main.main()
	/Users/michaeldesa/go/src/github.com/desa/fluxpanic/main.go:8 +0x36
exit status 2
```

**Comment by mark-rushakoff** [comment]
Maybe fixed by https://github.com/influxdata/flux/pull/483?

**Comment by desa** [comment]
yup
