### ISSUE TITLE
from |> range panics

### ISSUE THREAD

**Issue by rbetts** [influxdata/flux#773]
ip-192-168-1-6:flux-demo$ ./fluxd --version
fluxd version 2ee4157dedf07536b7aa659e3109e0f212789d9c

Running this query from chronograf crashed fluxd.

```
from(db: "telegraf")
	|> range(start: -10m)
```

```
goroutine 27 [running]:
net/http.(*conn).serve.func1(0xc420170000)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x17fc440, 0x1e50ff0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/influxdata/platform/query/execute.(*Allocator).Max(...)
	/go/src/github.com/influxdata/platform/query/execute/allocator.go:43
github.com/influxdata/platform/query/control.(*Query).Statistics(0xc420226000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/platform/query/control/controller.go:456 +0xcb
github.com/influxdata/platform/query.(*resultIterator).Statistics(0xc4202ae990, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/platform/query/query.go:178 +0x6b
github.com/influxdata/platform/http.(*QueryHandler).handlePostQuery(0xc4204c9ec0, 0x19b8c40, 0xc4202e0240, 0xc420132300)
	/go/src/github.com/influxdata/platform/http/query_service.go:134 +0x611
github.com/influxdata/platform/http.(*QueryHandler).(github.com/influxdata/platform/http.handlePostQuery)-fm(0x19b8c40, 0xc4202e0240, 0xc420132300)
	/go/src/github.com/influxdata/platform/http/query_service.go:42 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420334bb0, 0x19b8c40, 0xc4202e0240, 0xc420132300)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/influxdata/platform/vendor/github.com/julienschmidt/httprouter.(*Router).Handler.func1(0x19b8c40, 0xc4202e0240, 0xc420132200, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/platform/vendor/github.com/julienschmidt/httprouter/params_go17.go:26 +0x137
github.com/influxdata/platform/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4204c9e80, 0x19b8c40, 0xc4202e0240, 0xc420132200)
	/go/src/github.com/influxdata/platform/vendor/github.com/julienschmidt/httprouter/router.go:334 +0x770
github.com/influxdata/platform/http.(*Handler).ServeHTTP(0xc4204cd860, 0x19bb940, 0xc4201bc0e0, 0xc420132200)
	/go/src/github.com/influxdata/platform/http/handler.go:101 +0x1c1
net/http.serverHandler.ServeHTTP(0xc42015d860, 0x19bb940, 0xc4201bc0e0, 0xc420132200)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420170000, 0x19bc340, 0xc420146340)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
```

**Comment by russorat** [comment]
no longer seeing this behavior.
