### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#819]
```
from(bucket: "default")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "system")
  |> filter(fn: (r) => r._field == "uptime")
  |> window(period: 1s)
  |> last()
  |> toFloat()
  |> map(fn: (r) => r._value / 86400.0, mergeKey: true)
  |> group(columns: ["_value", "_time", "_start", "_stop"], mode: "except")
  |> yield(name: "last")
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x150ac5d]

goroutine 1 [running]:
github.com/influxdata/flux/semantic.(*CallExpression).Copy(0xc00013fc20, 0xc00018fa90, 0xc000457901)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/semantic/graph.go:583 +0x10d
github.com/influxdata/flux/semantic.(*FunctionBlock).Copy(0xc00025fbd0, 0xc0003d53c0, 0xc00000c080)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/semantic/graph.go:485 +0x93
github.com/influxdata/flux/semantic.(*FunctionExpression).Copy(0xc0002f4740, 0xc0004579b8, 0x1c1d320)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/semantic/graph.go:464 +0x8f
github.com/influxdata/flux/interpreter.function.Resolve(0xc0002f4740, 0xc0000b5ee0, 0xc0000b4a80, 0x19c6de0, 0x1ad1280, 0xc0000b5f01, 0x556bac0)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:985 +0x2f
github.com/influxdata/flux/interpreter.ResolveFunction(0x1c1d320, 0xc00000c080, 0x2, 0x1c1d320, 0xc00000c080)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:972 +0x67
github.com/influxdata/flux/functions/transformations.createMapOpSpec(0x1c1d7c0, 0xc0000b5fe0, 0xc00043c210, 0xc000457b10, 0x100e388, 0x20, 0x1a07660)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/functions/transformations/map.go:54 +0xc4
github.com/influxdata/flux.(*function).call(0xc0001ec180, 0x1c1d7c0, 0xc0000b5fe0, 0x155ef45, 0x1c1d940, 0xc0000b5f00, 0xc0000b5fe0)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/compile.go:615 +0x58
github.com/influxdata/flux.(*function).call-fm(0x1c1d7c0, 0xc0000b5fe0, 0x1c1d7c0, 0xc0000b5fe0, 0xc000457c58, 0x155a14c)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/compile.go:609 +0x3e
github.com/influxdata/flux/interpreter.DoFunctionCall(0xc000457c48, 0x1c1d940, 0xc0000b5f00, 0xc00030b1a0, 0xc00030b140, 0x1c18c20, 0xc0001520c0)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:570 +0x77
github.com/influxdata/flux.(*function).Call(0xc0001ec180, 0x1c1d940, 0xc0000b5f00, 0x1af2f04, 0x6, 0x1c14000, 0xc0002f4780)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/compile.go:609 +0x61
github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc0000b4a80, 0xc00013fc80, 0xc0000b5ee0, 0x0, 0x0, 0x100000000000000, 0x0)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:607 +0x2dd
github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc0000b4a80, 0x1c13e20, 0xc00013fc80, 0xc0000b5ee0, 0xc00013fc80, 0x1, 0x0, 0x0)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:379 +0x1746
github.com/influxdata/flux/interpreter.function.doCall(0xc0002f47c0, 0xc0001597c0, 0xc0000b4a80, 0x1c1d7c0, 0xc0000b5ec0, 0x1ad1280, 0x155a14c, 0xc0000b53c0, 0x18)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:937 +0x87c
github.com/influxdata/flux/interpreter.function.Call(0xc0002f47c0, 0xc0001597c0, 0xc0000b4a80, 0x1c1d940, 0xc0000b53c0, 0xc0004583a0, 0xc0000b5ea0, 0xc0000b5ea0, 0x1ad1280)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:896 +0x93
github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc0000b4a80, 0xc0000b9ce0, 0xc0000b4980, 0x0, 0x0, 0xc000484200, 0xc000458401)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:607 +0x2dd
github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc0000b4a80, 0x1c13e20, 0xc0000b9ce0, 0xc0000b4980, 0xc0001581c0, 0xc000158100, 0x0, 0x0)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:379 +0x1746
github.com/influxdata/flux/interpreter.(*Interpreter).doArguments(0xc0000b4a80, 0xc0000bef00, 0xc0000b4980, 0x1af2f04, 0x6, 0x1c13e20, 0xc0000b9ce0, 0x1af2f04, 0x6, 0x4, ...)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:639 +0x361
github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc0000b4a80, 0xc0000b9c80, 0xc0000b4980, 0x0, 0x0, 0xc0002ffd00, 0xc000458901)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:595 +0x275
github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc0000b4a80, 0x1c13e20, 0xc0000b9c80, 0xc0000b4980, 0xc0000b5280, 0xc0000b5200, 0x0, 0x0)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:379 +0x1746
github.com/influxdata/flux/interpreter.(*Interpreter).doArguments(0xc0000b4a80, 0xc0000bedc0, 0xc0000b4980, 0x1af2f04, 0x6, 0x1c13e20, 0xc0000b9c80, 0x1af2f04, 0x6, 0x8, ...)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:639 +0x361
github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc0000b4a80, 0xc0000b9bc0, 0xc0000b4980, 0x0, 0x0, 0xc0002ffa00, 0xc000458e01)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:595 +0x275
github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc0000b4a80, 0x1c13e20, 0xc0000b9bc0, 0xc0000b4980, 0xc0000b5180, 0xc0000b5100, 0x0, 0x0)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:379 +0x1746
github.com/influxdata/flux/interpreter.(*Interpreter).doArguments(0xc0000b4a80, 0xc0000bed20, 0xc0000b4980, 0x1af2f04, 0x6, 0x1c13e20, 0xc0000b9bc0, 0x1af2f04, 0x6, 0x7, ...)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:639 +0x361
github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc0000b4a80, 0xc0000b9980, 0xc0000b4980, 0x0, 0x0, 0x1a16600, 0xc0000b9920)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:595 +0x275
github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc0000b4a80, 0x1c13e20, 0xc0000b9980, 0xc0000b4980, 0x8020104, 0x4, 0x1af07fb, 0x202030203030302)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:379 +0x1746
github.com/influxdata/flux/interpreter.(*Interpreter).doStatement(0xc0000b4a80, 0x1c13e80, 0xc00042b780, 0xc0000b4980, 0x203000, 0x203000, 0x2, 0x25c5260)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:324 +0x365
github.com/influxdata/flux/interpreter.(*Interpreter).doFile(0xc0000b4a80, 0xc0001961c0, 0x0, 0x0, 0xc00000e0a0, 0x0)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:271 +0x163
github.com/influxdata/flux/interpreter.(*Interpreter).doPackage(0xc0000b4a80, 0xc0000b9920, 0x0, 0x0, 0x1523049, 0x1c05e60)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:255 +0x84
github.com/influxdata/flux/interpreter.(*Interpreter).doRoot(0xc0000b4a80, 0x1c113a0, 0xc0000b9920, 0x0, 0x0, 0xc0004df560, 0x0)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:238 +0x137
github.com/influxdata/flux/interpreter.(*Interpreter).Eval(0xc0000b4a80, 0x1c113a0, 0xc0000b9920, 0x0, 0x0, 0x1861c8d, 0x0)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/interpreter/interpreter.go:232 +0x2c6
github.com/influxdata/flux/repl.(*REPL).executeLine(0xc00031c510, 0xc000530180, 0x164, 0x0, 0xc0006b39d0, 0x18689c8, 0xc00031e000)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/repl/repl.go:152 +0xc9
github.com/influxdata/flux/repl.(*REPL).input(0xc00031c510, 0xc000530180, 0x164)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/repl/repl.go:119 +0x49
github.com/influxdata/flux/repl.(*REPL).input-fm(0xc000530180, 0x164)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/repl/repl.go:50 +0x3e
github.com/c-bata/go-prompt.(*Prompt).Run(0xc000126000)
	/Users/rsavage/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.2/prompt.go:81 +0x63f
github.com/influxdata/flux/repl.(*REPL).Run(0xc00031c510)
	/Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.13.0/repl/repl.go:62 +0x1d9
main.replF(0x2367c60, 0xc000158320, 0x0, 0x2)
	/Users/rsavage/go/src/github.com/influxdata/influxdb/cmd/influx/repl.go:86 +0x156
github.com/spf13/cobra.(*Command).execute(0x2367c60, 0xc000158240, 0x2, 0x2, 0x2367c60, 0xc000158240)
	/Users/rsavage/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x23672e0, 0x1af56ad, 0x9, 0x1af6e15)
	/Users/rsavage/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x23672e0, 0x1007500, 0xc000094058)
	/Users/rsavage/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
main.Execute()
	/Users/rsavage/go/src/github.com/influxdata/influxdb/cmd/influx/main.go:91 +0x2d
main.main()
	/Users/rsavage/go/src/github.com/influxdata/influxdb/cmd/influx/main.go:15 +0x20
```

**Comment by reloxx13** [comment]
got the same :X

do u need more infos?

```
from(bucket: "iobroker/global")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r._measurement == "temp.ventilator")
  |> window(every: autoInterval)
  |> mean()
  |> group(columns: ["_value"], mode: "except")
```

**Comment by aanthony1243** [comment]
@russorat I tried your query on the latest code from master and there's no panic. please re-open if you still have problems.
