### ISSUE TITLE
panic: building histogram

### ISSUE THREAD

**Issue by goller** [influxdata/flux#900]
query:

```f#
  from(bucket:"goller")
    |> range(start:timeRangeStart)
    |> filter(fn:(r) => r._measurement == "query_control_all_duration_seconds" and r._field != "sum" and r._field != "count")
    |> limit(n:1)
    |> map(fn:(r) => ({
        upperBound: float(v:r._field),
        _value: r._value,
    }))
    |> group(columns:["_time","_field","_value","url","host","org"], mode: "except")
    |> sum() // sum across orgs
    |> group(columns:["_time","_value","upperBound"], mode: "except")
    |> histogramQuantile(quantile:0.99)
    |> yield()
```
Here is the top of the attached panic:

```
2019/01/19 12:42:02 Internal error: runtime error: invalid memory address or nil pointer dereference
2019/01/19 12:42:02 goroutine 219 [running]:
github.com/influxdata/influxdb/http.panicHandler(0x2395ea0, 0xc001372120, 0xc000134900, 0x1f99880, 0x3182ce0)
	/Users/goller/src/go/src/github.com/influxdata/influxdb/http/router.go:50 +0xe5
github.com/julienschmidt/httprouter.(*Router).recv(0xc001b32f80, 0x2395ea0, 0xc001372120, 0xc000134900)
	/Users/goller/src/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:270 +0x79
panic(0x1f99880, 0x3182ce0)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/flux/semantic.(*CallExpression).Copy(0xc0002b6e00, 0xc00060bbc0, 0x10)
	/Users/goller/src/go/pkg/mod/github.com/influxdata/flux@v0.16.1/semantic/graph.go:635 +0x10d
github.com/influxdata/flux/semantic.(*Property).Copy(0xc000f49920, 0x2, 0x2)
	/Users/goller/src/go/pkg/mod/github.com/influxdata/flux@v0.16.1/semantic/graph.go:790 +0x85
github.com/influxdata/flux/semantic.(*ObjectExpression).Copy(0xc000f497a0, 0xc00060b9e0, 0xc001bc0701)
	/Users/goller/src/go/pkg/mod/github.com/influxdata/flux@v0.16.1/semantic/graph.go:746 +0x118
github.com/influxdata/flux/semantic.(*FunctionBlock).Copy(0xc000f49a40, 0xc000b578b0, 0xc0018bbe90)
```

Here is the line of code:

https://github.com/influxdata/flux/blob/5bbc9050eff02d4ecf90ac458b72b0213a299c41/semantic/graph.go#L635

[panic.txt](https://github.com/influxdata/flux/files/2775857/panic.txt)

**Comment by wolffcm** [comment]
Seems like another dupe of #894.

**Comment by goller** [comment]
@wolffcm thanks!
