### ISSUE TITLE
panic: interface conversion: interface {} is nil, not float64

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#936]
running influxdb master 559cbc776eb8c59d160ee4fd30983082702f5504

```
panic: interface conversion: interface {} is nil, not float64
 goroutine 9403 [running]:
 runtime/debug.Stack(0x1fd2b60, 0x1fcf6a0, 0xc001f5f3e0)
 /usr/local/Cellar/go/1.11.4/libexec/src/runtime/debug/stack.go:24 +0xa7
 github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc00354fc20)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/execute/dispatcher.go:73 +0xbc
 panic(0x1fcf6a0, 0xc001f5f3e0)
 /usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
 github.com/influxdata/flux/values.value.Float(0x23d9460, 0x23a9cd0, 0x0, 0x0, 0xc005bcf301)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/values/values.go:61 +0x8c
 github.com/influxdata/flux/compiler.(*memberEvaluator).EvalFloat(0xc001f5f110, 0xc001f5f140, 0xc006e279f0)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/compiler/runtime.go:953 +0x81
 github.com/influxdata/flux/compiler.eval(0x23df900, 0xc001f5f110, 0xc001f5f140, 0x23d9460, 0xc00562eee8)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/compiler/runtime.go:237 +0x2b9
 github.com/influxdata/flux/compiler.(*binaryEvaluator).eval(0xc003af6e80, 0xc001f5f140, 0x23d9460, 0x13dea4c, 0x6, 0x6)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/compiler/runtime.go:502 +0x46
 github.com/influxdata/flux/compiler.(*binaryEvaluator).EvalBool(0xc003af6e80, 0xc001f5f140, 0x23d8f20)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/compiler/runtime.go:518 +0x39
 github.com/influxdata/flux/compiler.compiledFn.Eval(0x23df400, 0xc003af6e80, 0x23d8f20, 0xc00408e080, 0xc001f5f140, 0x23e3ce0, 0xc0030f0090, 0xc0030f00c0, 0x2f14a32, 0x1, ...)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/compiler/runtime.go:92 +0x4f0
 github.com/influxdata/flux/execute.(*rowFn).eval(0xc00354fd40, 0x2, 0x23dc700, 0xc002993f40, 0x0, 0x0, 0x5, 0x6)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/execute/row_fn.go:121 +0x1c8
 github.com/influxdata/flux/execute.(*RowPredicateFn).Eval(0xc00354fd40, 0x2, 0x23dc700, 0xc002993f40, 0xc001d16370, 0x0, 0x0)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/execute/row_fn.go:150 +0x4f
 github.com/influxdata/flux/stdlib/universe.(*filterTransformation).Process.func1(0x23dc700, 0xc002993f40, 0x1, 0xc005bcf7c0)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/stdlib/universe/filter.go:152 +0xb1
 github.com/influxdata/flux/execute.(*ColListTable).Do(0xc002993f40, 0xc005bcf7c0, 0x6, 0x8)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/execute/table.go:1303 +0x3c
 github.com/influxdata/flux/stdlib/universe.(*filterTransformation).Process(0xc0030f0150, 0xd55acd19245843ee, 0x9d657717faaf5689, 0x23d4ea0, 0xc002993f40, 0x103ee01, 0xc00354fb58)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/stdlib/universe/filter.go:149 +0x159
 github.com/influxdata/flux/execute.processMessage(0x23d02a0, 0xc0030f0150, 0x23bb020, 0xc003280da0, 0xc002892f68, 0x10dde3d, 0xc006f16510)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/execute/transport.go:199 +0x1fc
 github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc00354fda0, 0xa)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/execute/transport.go:156 +0xa1
 github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages-fm(0xa)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/execute/transport.go:137 +0x34
 github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc00354fc20, 0x23caea0, 0xc0043ade30)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/execute/dispatcher.go:126 +0x4b
 github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc00354fc20, 0x23caea0, 0xc0043ade30)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/execute/dispatcher.go:80 +0x95
 created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.17.0/execute/dispatcher.go:61 +0x7e
```

```
from(bucket: "prom_server")
  |> range(start: timeRangeStart)
  |> filter(fn: (r) => r._measurement =~ /go_memstats.*/)
  |> filter(fn: (r) => r._field == "gauge")
  |> derivative(unit: windowPeriod, nonNegative: true)
  |> filter(fn: (r) => r._value > 0)
  |> yield(name: "derivative")
```

**Comment by jsternberg** [comment]
This is being handled by #862. We will revisit how nulls should be handled in the future, but the panic should be gone which resolves this issue.

**Comment by russorat** [comment]
i'm still seeing this in cloud.

```
option task = {name: "new test", cron: "* * * * *"}

from(bucket: "bbbbbb")
	|> range(start: -5m)
	|> filter(fn: (r) =>
		(r._measurement == "mmmmmmm" and r._field == "fffffff"))
	|> group(columns: ["dc", "datacenter"])
	|> aggregateWindow(every: 1m, fn: mean)
	|> to(bucket: "bucket", org: "user_org")
```

```
2019-04-17 13:38:02
Run failed to execute: panic: interface conversion: interface {} is nil, not float64
goroutine 991631 [running]:
runtime/debug.Stack(0x17f6b60, 0x17f35a0, 0xc0002a89c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc003f81080)
	/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/dispatcher.go:73 +0xbc
panic(0x17f35a0, 0xc0002a89c0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/flux/values.value.Float(0x1dfee40, 0x1db9b40, 0x0, 0x0, 0x1db9b40)
	/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/values/values.go:67 +0x8c
github.com/influxdata/idpe/query/stdlib/influxdata/influxdb.writeTable.func1(0x1e052c0, 0xc00577f360, 0xc00cc45801, 0xc002956000)
	/go/src/github.com/influxdata/idpe/query/stdlib/influxdata/influxdb/to.go:356 +0xcd7
github.com/influxdata/flux/execute.(*ColListTable).Do(0xc00577f360, 0xc002956000, 0x10, 0x8)
	/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/table.go:1301 +0x3c
github.com/influxdata/idpe/query/stdlib/influxdata/influxdb.writeTable(0xc0024b2700, 0x1df32a0, 0xc00577f360, 0xc000f85c50, 0xc000f85d09)
	/go/src/github.com/influxdata/idpe/query/stdlib/influxdata/influxdb/to.go:278 +0x553
github.com/influxdata/idpe/query/stdlib/influxdata/influxdb.(*ToTransformation).Process(0xc0024b2700, 0xca5554be02cd9dea, 0xedec76c6af6621b6, 0x1df32a0, 0xc00577f360, 0x43d301, 0xc003f80fb8)
	/go/src/github.com/influxdata/idpe/query/stdlib/influxdata/influxdb/to.go:115 +0x8d
github.com/influxdata/flux/execute.processMessage(0x1df4ae0, 0xc0024b2700, 0x1dcf8a0, 0xc0024216e0, 0xc000f85f68, 0x4e606d, 0xc002608ed0)
	/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/transport.go:199 +0x1fc
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc003f81260, 0xa)
	/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/transport.go:156 +0xa1
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages-fm(0xa)
	/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/transport.go:137 +0x34
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc003f81080, 0x1dee6a0, 0xc000da1320)
	/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/dispatcher.go:126 +0x4b
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc003f81080, 0x1dee6a0, 0xc000da1320)
	/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/dispatcher.go:80 +0x95
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/go/src/github.com/influxdata/idpe/vendor/github.com/influxdata/flux/execute/dispatcher.go:61 +0x7e
2019-04-17 13:38:02
Failed
```
