### ISSUE TITLE
Panic when omitting parentheses on function call

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#969]
When using InfluxDB 2.0.0-alpha.2 (commit 9aeca07e9), I get a panic when omitting parentheses on a function call. E.g.:

```
from(bucket: "prometheus")
  |> range
```

The logged panic message:

```
runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 9636 [running]:
runtime/debug.Stack(0xc000fda740, 0xc003ac1780, 0x40)
  /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/http.panicHandler(0x17f45e0, 0xc002bb2020, 0xc00011f200, 0x13e97c0, 0x2579020)
  /go/src/github.com/influxdata/influxdb/http/router.go:62 +0x234
github.com/julienschmidt/httprouter.(*Router).recv(0xc001ea3240, 0x17f45e0, 0xc002bb2020, 0xc00011f200)
  /go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:270 +0x79
panic(0x13e97c0, 0x2579020)
  /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/flux/semantic.analyzeCallExpression(0x0, 0xc002a82480, 0x40, 0xc0018f4b78)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/semantic/analyze.go:390 +0x37
github.com/influxdata/flux/semantic.analyzePipeExpression(0xc002a82480, 0x769dce, 0xc002bb2800, 0x1803740)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/semantic/analyze.go:456 +0x33
github.com/influxdata/flux/semantic.analyzeExpression(0x1807ac0, 0xc002a82480, 0xf19e381e4ab6a701, 0xf100000000000008, 0xc0018f4d00, 0x7c9f4d)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/semantic/analyze.go:254 +0x6b0
github.com/influxdata/flux/semantic.analyzeExpressionStatement(0xc002d1ea50, 0x0, 0x0, 0xc0018f4d80)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/semantic/analyze.go:189 +0x4d
github.com/influxdata/flux/semantic.analyzeStatment(0x1807640, 0xc002d1ea50, 0x1, 0xc000fda730, 0x1, 0x1)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/semantic/analyze.go:125 +0x612
github.com/influxdata/flux/semantic.analyzeFile(0xc002bb4230, 0xc002bb42a0, 0x1, 0xc0019b6078)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/semantic/analyze.go:62 +0x384
github.com/influxdata/flux/semantic.analyzePackage(0xc000b59860, 0x40bb8f, 0xc002d1eb40, 0x30)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/semantic/analyze.go:31 +0x10a
github.com/influxdata/flux/semantic.New(0xc000b59860, 0x0, 0xc000302e00, 0x0)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/semantic/analyze.go:13 +0x2f
github.com/influxdata/flux.EvalAST(0xc000b59860, 0xc0018f5140, 0x1, 0x1, 0xc002d1eb40, 0x0, 0x0, 0x1810040, 0xc001315dd0, 0x17f9d60, ...)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/compile.go:114 +0x40
github.com/influxdata/flux.CompileAST(0x17f9d60, 0xc002d1e900, 0xc000b59860, 0xbf1130260b70f8e6, 0x1df504c7ef, 0x25bf7c0, 0x0, 0x0, 0x0, 0x0, ...)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/compile.go:63 +0x1bf
github.com/influxdata/flux.Compile(0x17f9d60, 0xc002d1e900, 0xc001eabb60, 0x29, 0xbf1130260b70f8e6, 0x1df504c7ef, 0x25bf7c0, 0x0, 0x0, 0x0, ...)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/compile.go:50 +0xda
github.com/influxdata/flux/lang.FluxCompiler.Compile(0xc001eabb60, 0x29, 0x17f9d60, 0xc002d1e900, 0xc000302e01, 0x0, 0xc000386fe8)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/lang/compiler.go:36 +0x89
github.com/influxdata/flux/control.(*Controller).compileQuery(0xc0001c2a90, 0xc000386f00, 0x17eed60, 0xc000fda600, 0x4, 0xc000386f00)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/control/controller.go:175 +0x8b
github.com/influxdata/flux/control.(*Controller).Query(0xc0001c2a90, 0x17f9d60, 0xc002d1e7b0, 0x17eed60, 0xc000fda600, 0xc000fda630, 0x17f9d60, 0xc002d1e7b0, 0x40c418)
  /go/pkg/mod/github.com/influxdata/flux@v0.18.0/control/controller.go:114 +0x9c
github.com/influxdata/influxdb/query/control.(*Controller).Query(0xc00000c1c0, 0x17f9d60, 0xc002d1e780, 0xc002a82080, 0xc003354d44, 0x15ecd52, 0x1, 0x0)
  /go/src/github.com/influxdata/influxdb/query/control/controller.go:35 +0x138
github.com/influxdata/influxdb/query.QueryServiceBridge.Query(0x17e4d80, 0xc00000c1c0, 0x17f9d60, 0xc002d1e690, 0xc002a82080, 0x2c00000004, 0x8, 0x10, 0xc000fda620)
  /go/src/github.com/influxdata/influxdb/query/bridges.go:19 +0x56
github.com/influxdata/influxdb/query.ProxyQueryServiceBridge.Query(0x17e6920, 0xc000bb24e0, 0x17f9d60, 0xc002d1e690, 0x7f8da3295a80, 0xc002bb2020, 0xc002a82080, 0x0, 0x0, 0x0)
  /go/src/github.com/influxdata/influxdb/query/bridges.go:32 +0x8c
github.com/influxdata/influxdb/http.(*FluxHandler).handleQuery(0xc001ea3280, 0x17f45e0, 0xc002bb2020, 0xc00011f300)
  /go/src/github.com/influxdata/influxdb/http/query_handler.go:102 +0x314
github.com/influxdata/influxdb/http.(*FluxHandler).handleQuery-fm(0x17f45e0, 0xc002bb2020, 0xc00011f300)
  /go/src/github.com/influxdata/influxdb/http/query_handler.go:71 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0020f8360, 0x17f45e0, 0xc002bb2020, 0xc00011f300)
  /usr/local/go/src/net/http/server.go:1964 +0x44
github.com/julienschmidt/httprouter.(*Router).Handler.func1(0x17f45e0, 0xc002bb2020, 0xc00011f200, 0x0, 0x0, 0x0)
  /go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/params_go17.go:26 +0x1c7
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc001ea3240, 0x17f45e0, 0xc002bb2020, 0xc00011f200)
  /go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x792
github.com/influxdata/influxdb/http.(*APIHandler).ServeHTTP(0xc0001e6320, 0x17f45e0, 0xc002bb2020, 0xc00011f200)
  /go/src/github.com/influxdata/influxdb/http/api_handler.go:223 +0x998
github.com/influxdata/influxdb/http.(*AuthenticationHandler).ServeHTTP(0xc001ea25c0, 0x17f45e0, 0xc002bb2020, 0xc00011f000)
  /go/src/github.com/influxdata/influxdb/http/authentication_middleware.go:94 +0x258
github.com/influxdata/influxdb/http.(*PlatformHandler).ServeHTTP(0xc0024a1fa0, 0x17f45e0, 0xc002bb2020, 0xc00011f000)
  /go/src/github.com/influxdata/influxdb/http/platform_handler.go:70 +0xd2
github.com/influxdata/influxdb/http.(*Handler).ServeHTTP(0xc000925b00, 0x17f7c60, 0xc0001d00e0, 0xc00011f000)
  /go/src/github.com/influxdata/influxdb/http/handler.go:166 +0x21a
net/http.serverHandler.ServeHTTP(0xc000167110, 0x17f7c60, 0xc0001d00e0, 0xc00011ef00)
  /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc002d96be0, 0x17f9ca0, 0xc003d13780)
  /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
  /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by aanthony1243** [comment]
traced this down to here: https://github.com/influxdata/flux/blob/5f036df987f229028b3002d6439d1692d729822e/internal/parser/parser.go#L584

in general, we need to overhaul the parser error handling and this will be fixed in that effort.  we could put nil checks in the compiler analyzer, but it may be a better approach to assume that AST is always valid with non-nil values and put our effort in there.
