### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#978]
```
from(bucket: "trial_started")
  |> range(start: 0)
  |> filter(fn: (r) => r._measurement == "trials")
  |> map(fn:(r) => float(v: r.week))
  |> duplicate(column: "_value", as: "week_num")
  |> map(fn:(r) => float(v: r.month))
  |> duplicate(column: "_value", as: "month_num")
```

```
panic: runtime error: invalid memory address or nil pointer dereference
 goroutine 170082 [running]:
 runtime/debug.Stack(0x1fed540, 0x1fdbc40, 0x2f83350)
 /usr/local/Cellar/go/1.11.5/libexec/src/runtime/debug/stack.go:24 +0xa7
 github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc0068fcea0)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/execute/dispatcher.go:73 +0xbc
 panic(0x1fdbc40, 0x2f83350)
 /usr/local/Cellar/go/1.11.5/libexec/src/runtime/panic.go:513 +0x1b9
 github.com/influxdata/flux/compiler.(*callEvaluator).EvalFloat(0xc000afde00, 0xc000afde30, 0x23f9f60)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/compiler/runtime.go:1114 +0x3f
 github.com/influxdata/flux/compiler.compiledFn.Eval(0x2400740, 0xc000afde00, 0x23f9f60, 0xc0058ce280, 0xc000afde30, 0x2404f20, 0xc006ae4180, 0xc006ae41b0, 0x2f44a52, 0x1, ...)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/compiler/runtime.go:90 +0x400
 github.com/influxdata/flux/execute.(*rowFn).eval(0xc00283d110, 0x0, 0x23fd740, 0xc007414eb0, 0x98, 0x203000, 0x203000, 0xc000afdef0)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/execute/row_fn.go:126 +0x20e
 github.com/influxdata/flux/execute.(*RowMapFn).Eval(0xc00283d110, 0x0, 0x23fd740, 0xc007414eb0, 0xc00698f450, 0x20bc0c0, 0x18, 0xc0069a5b78)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/execute/row_fn.go:242 +0x4f
 github.com/influxdata/flux/stdlib/universe.(*mapTransformation).Process.func1(0x23fd740, 0xc007414eb0, 0x1, 0xc00698f450)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/stdlib/universe/map.go:171 +0xff
 github.com/influxdata/flux/execute.(*ColListTable).Do(0xc007414eb0, 0xc00698f450, 0xc006b5add0, 0x4)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/execute/table.go:1303 +0x3c
 github.com/influxdata/flux/stdlib/universe.(*mapTransformation).Process(0xc006ae4240, 0xd4556c7d2de7fb53, 0x51c066366d49d2a1, 0x23f5ee0, 0xc007414eb0, 0x103ee01, 0xc0068fcdd8)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/stdlib/universe/map.go:168 +0x43f
 github.com/influxdata/flux/execute.processMessage(0x23f1140, 0xc006ae4240, 0x23dba00, 0xc005534380, 0xc004587f68, 0x10dde3d, 0xc0068deb90)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/execute/transport.go:199 +0x1fc
 github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc0068fcfc0, 0xa)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/execute/transport.go:156 +0xa1
 github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages-fm(0xa)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/execute/transport.go:137 +0x34
 github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc0068fcea0, 0x23eb900, 0xc006071bc0)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/execute/dispatcher.go:126 +0x4b
 github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc0068fcea0, 0x23eb900, 0xc006071bc0)
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/execute/dispatcher.go:80 +0x95
 created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
 /Users/rsavage/go/pkg/mod/github.com/influxdata/flux@v0.19.0/execute/dispatcher.go:61 +0x7e
```

**Comment by jlapacik** [comment]
Fixed by #1018 .
